<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger/options.proto

namespace LiveKit\Proto\Meta\Logger;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA4\x02\x0A\x14logger/options.proto\x12\x06logger\x1A google/protobuf/descriptor.proto*W\x0A\x0BSensitivity\x12\x1B\x0A\x17SENSITIVITY_UNSPECIFIED\x10\x00\x12\x13\x0A\x0FSENSITIVITY_PII\x10\x01\x12\x16\x0A\x12SENSITIVITY_SECRET\x10\x02B\x80\x01Z*github.com/livekit/protocol/livekit/logger\xAA\x02\x0DLiveKit.Proto\xCA\x02\x14LiveKit\\Proto\\Logger\xE2\x02\x19LiveKit\\Proto\\Meta\\Logger\xEA\x02\x0ELiveKit::Protob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

