<?php

declare(strict_types=1);

namespace LiveKit\Tests\Integration;

use Firebase\JWT\JWT;
use LiveKit\AccessToken;
use LiveKit\Exceptions\TwirpErrorCode;
use LiveKit\Exceptions\TwirpException;
use LiveKit\Grants\VideoGrant;
use LiveKit\LiveKitAPI;
use LiveKit\Options\AccessTokenOptions;
use LiveKit\Options\ClientOptions;
use LiveKit\Options\CreateRoomOptions;
use LiveKit\Tests\Integration\Support\IntegrationTestCase;
use LiveKit\TokenVerifier;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * Proves that a token this package mints is one a real LiveKit deployment
 * accepts, and that the grant on it means what the grant table says.
 *
 * The unit suite checks the claim layout against JWTs produced by LiveKit's own
 * Go implementation, which is strong evidence about the *shape* and none at all
 * about whether a server honours it. These tests mint a token, hand it to the
 * client verbatim through ClientOptions::$token, and let the deployment decide --
 * which is the only way to learn that a grant this SDK spells one way is read the
 * way it was meant.
 *
 * WebhookReceiver is deliberately absent. Verifying it end to end needs LiveKit
 * to POST a signed webhook to a publicly reachable URL, which a test suite has no
 * way to stand up. What it rests on instead: the body fixture the unit suite
 * checks against is generated by LiveKit's own webhook/url_notifier.go, so it is
 * byte-exact against the code the server runs, and the HS256 signing and
 * verification underneath it is the same machinery these tests prove a live
 * server accepts.
 */
final class AccessTokenIntegrationTest extends IntegrationTestCase
{
    /** @return array{string, string, string} host, key, secret */
    private function credentials(): array
    {
        return [
            (string) getenv('LIVEKIT_URL'),
            (string) getenv('LIVEKIT_API_KEY'),
            (string) getenv('LIVEKIT_API_SECRET'),
        ];
    }

    /** Builds a client that sends exactly this grant, and nothing the SDK would have added. */
    private function clientFor(VideoGrant $grant, ?string $secretOverride = null): LiveKitAPI
    {
        [$host, $key, $secret] = $this->credentials();

        $token = new AccessToken($key, $secretOverride ?? $secret, new AccessTokenOptions(identity: 'integration-probe'));
        $token->addGrant($grant);

        return new LiveKitAPI(host: $host, options: new ClientOptions(token: $token->toJwt(), failover: false));
    }

    /** @return iterable<string, array{VideoGrant, callable(LiveKitAPI): mixed}> */
    public static function grantsAndTheCallsTheyPermit(): iterable
    {
        yield 'roomList lists rooms' => [
            new VideoGrant(roomList: true),
            static fn (LiveKitAPI $api): mixed => $api->room->listRooms(),
        ];
        yield 'ingressAdmin lists ingress' => [
            new VideoGrant(ingressAdmin: true),
            static fn (LiveKitAPI $api): mixed => $api->ingress->listIngress(),
        ];
        yield 'roomRecord lists egress' => [
            new VideoGrant(roomRecord: true),
            static fn (LiveKitAPI $api): mixed => $api->egress->listEgress(),
        ];
    }

    /** @param callable(LiveKitAPI): mixed $call */
    #[DataProvider('grantsAndTheCallsTheyPermit')]
    public function test_a_grant_this_sdk_mints_is_accepted_by_the_server(VideoGrant $grant, callable $call): void
    {
        $this->skipIfUnavailable(fn (): mixed => $call($this->clientFor($grant)), 'The service');
        self::addToAssertionCount(1);
    }

    /**
     * The same call with a token that is perfectly valid but carries a different
     * grant. Note the empty metadata: this refusal came from LiveKit itself, which
     * is what separates it from the two below.
     */
    #[DataProvider('grantsAndTheCallsTheyPermit')]
    public function test_the_same_call_without_its_grant_is_refused_by_livekit_itself(VideoGrant $grant, callable $call): void
    {
        // A grant that is real, signed correctly, and wrong for this call.
        $client = $this->clientFor(new VideoGrant(roomCreate: true));

        try {
            $this->skipIfUnavailable(fn (): mixed => $call($client), 'The service');
        } catch (TwirpException $e) {
            self::assertSame(TwirpErrorCode::UNAUTHENTICATED, $e->getTwirpCode(), 'a missing grant is unauthenticated, not permission_denied');
            self::assertArrayNotHasKey(
                TwirpErrorCode::META_FROM_INTERMEDIARY,
                $e->getMeta(),
                'LiveKit answered this itself, so nothing marks it as coming from in front of it'
            );

            return;
        }

        self::fail('a call the token carries no grant for should not have succeeded');
    }

    public function test_room_admin_is_scoped_to_the_room_named_in_the_grant(): void
    {
        $granted = $this->scratchName('granted');
        $other = $this->scratchName('other');

        $this->cleanUpAfter(
            body: function () use ($granted, $other): void {
                $this->livekit->room->createRoom(new CreateRoomOptions(name: $granted, emptyTimeout: 30));
                $this->livekit->room->createRoom(new CreateRoomOptions(name: $other, emptyTimeout: 30));

                $client = $this->clientFor(new VideoGrant(roomAdmin: true, room: $granted));

                self::assertSame([], $client->room->listParticipants($granted), 'the room named in the grant is reachable');

                try {
                    $client->room->listParticipants($other);
                } catch (TwirpException $e) {
                    self::assertSame(TwirpErrorCode::UNAUTHENTICATED, $e->getTwirpCode(), $e->getMessage());

                    return;
                }

                self::fail('roomAdmin reached a room its grant does not name');
            },
            cleanup: function () use ($granted, $other): void {
                $this->livekit->room->deleteRoom($granted);
                $this->livekit->room->deleteRoom($other);
            },
            describe: sprintf('rooms "%s" and "%s"', $granted, $other),
        );
    }

    /** @return iterable<string, array{callable(self): string}> */
    public static function credentialsTheServerRejects(): iterable
    {
        // AccessToken refuses to mint an expired token -- a non-positive TTL is a
        // configuration error, asserted separately below -- so this one is signed
        // by hand in the same claim shape. What is under test is the server's
        // refusal and how this SDK surfaces it.
        yield 'expired' => [static function (self $test): string {
            [, $key, $secret] = $test->credentialsForProvider();
            $now = time();

            return JWT::encode([
                'iss' => $key,
                'sub' => 'integration-probe',
                'nbf' => $now - 7200,
                'exp' => $now - 3600,
                'iat' => $now - 7200,
                'video' => ['roomList' => true],
            ], $secret, 'HS256');
        }];

        yield 'signed with the wrong secret' => [static function (self $test): string {
            [, $key] = $test->credentialsForProvider();
            $token = new AccessToken($key, str_repeat('x', 40), new AccessTokenOptions(identity: 'integration-probe'));
            $token->addGrant(new VideoGrant(roomList: true));

            return $token->toJwt();
        }];
    }

    /**
     * The providers are static, so they reach the credentials through an instance.
     *
     * @return array{string, string, string} host, key, secret
     */
    public function credentialsForProvider(): array
    {
        return $this->credentials();
    }

    /**
     * A credential the auth layer rejects never reaches Twirp, so the 401 comes
     * back as a bare HTTP response rather than an error envelope. This SDK maps it
     * to unauthenticated and marks where it came from -- the only thing that tells
     * it apart from the grant failure above, which carries the same code.
     *
     * @param callable(self): string $mint
     */
    #[DataProvider('credentialsTheServerRejects')]
    public function test_a_credential_the_server_rejects_is_marked_as_coming_from_an_intermediary(callable $mint): void
    {
        [$host] = $this->credentials();

        $client = new LiveKitAPI(host: $host, options: new ClientOptions(token: $mint($this), failover: false));

        try {
            $client->room->listRooms();
        } catch (TwirpException $e) {
            self::assertSame(TwirpErrorCode::UNAUTHENTICATED, $e->getTwirpCode(), $e->getMessage());
            self::assertSame('true', $e->getMeta()[TwirpErrorCode::META_FROM_INTERMEDIARY] ?? null, 'the refusal came from in front of Twirp');
            self::assertSame('401', $e->getMeta()['status_code'] ?? null);

            return;
        }

        self::fail('a rejected credential should not have been accepted');
    }

    public function test_a_token_the_server_accepted_verifies_locally_too(): void
    {
        $room = $this->scratchName('verify');
        [, $key, $secret] = $this->credentials();

        $token = new AccessToken($key, $secret, new AccessTokenOptions(identity: 'integration-probe', name: 'Probe'));
        $token->addGrant(new VideoGrant(roomList: true, roomAdmin: true, room: $room));
        $jwt = $token->toJwt();

        // The server accepts it...
        [$host] = $this->credentials();
        $client = new LiveKitAPI(host: $host, options: new ClientOptions(token: $jwt, failover: false));
        $client->room->listRooms();

        // ...and so does the verifier in this package, reading back what was put in.
        $claims = new TokenVerifier($key, $secret)->verify($jwt);

        self::assertSame($key, $claims['iss'], 'iss is the api key');
        self::assertSame('integration-probe', $claims['sub'], 'sub is the identity');
        self::assertSame('Probe', $claims['name']);
        $video = $claims['video'];

        self::assertIsArray($video, 'the video grant is a nested object in the flat payload');
        self::assertTrue($video['roomList']);
        self::assertSame($room, $video['room'], 'the grant is room-scoped in the claims too');
        self::assertArrayHasKey('exp', $claims);
        self::assertArrayHasKey('nbf', $claims);
        self::assertArrayNotHasKey('jti', $claims, 'LiveKit tokens carry no jti');
    }

    public function test_the_sdk_refuses_to_mint_a_token_that_is_already_expired(): void
    {
        [, $key, $secret] = $this->credentials();

        $token = new AccessToken($key, $secret, new AccessTokenOptions(identity: 'integration-probe', ttl: '0s'));
        $token->addGrant(new VideoGrant(roomList: true));

        $this->expectException(\LiveKit\Exceptions\ConfigurationException::class);

        $token->toJwt();
    }
}
