<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * @deprecated
 * Generated from protobuf message <code>livekit.ActiveSpeakerUpdate</code>
 */
class ActiveSpeakerUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.SpeakerInfo speakers = 1;</code>
     */
    private $speakers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\LiveKit\Proto\SpeakerInfo>|\Google\Protobuf\RepeatedField $speakers
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SpeakerInfo speakers = 1;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getSpeakers()
    {
        return $this->speakers;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SpeakerInfo speakers = 1;</code>
     * @param array<\LiveKit\Proto\SpeakerInfo>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setSpeakers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SpeakerInfo::class);
        $this->speakers = $arr;

        return $this;
    }

}

