<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Unified audio selection and channel routing.
 * Each route specifies both which audio to capture and which channel to output to.
 *
 * Generated from protobuf message <code>livekit.AudioConfig</code>
 */
class AudioConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * If true, all unmatched audio is recorded to both channels
     *
     * Generated from protobuf field <code>bool capture_all = 1;</code>
     */
    protected $capture_all = false;
    /**
     * Generated from protobuf field <code>repeated .livekit.AudioRoute routes = 2;</code>
     */
    private $routes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $capture_all
     *           If true, all unmatched audio is recorded to both channels
     *     @type \LiveKit\Proto\AudioRoute[] $routes
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * If true, all unmatched audio is recorded to both channels
     *
     * Generated from protobuf field <code>bool capture_all = 1;</code>
     * @return bool
     */
    public function getCaptureAll()
    {
        return $this->capture_all;
    }

    /**
     * If true, all unmatched audio is recorded to both channels
     *
     * Generated from protobuf field <code>bool capture_all = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCaptureAll(bool $var)
    {
        $this->capture_all = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.AudioRoute routes = 2;</code>
     * @return RepeatedField<\LiveKit\Proto\AudioRoute>
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.AudioRoute routes = 2;</code>
     * @param \LiveKit\Proto\AudioRoute[] $var
     * @return $this
     */
    public function setRoutes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\AudioRoute::class);
        $this->routes = $arr;

        return $this;
    }

}

