<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.AutoTrackEgress</code>
 */
class AutoTrackEgress extends \Google\Protobuf\Internal\Message
{
    /**
     * see docs for templating (default {track_id}-{time})
     *
     * Generated from protobuf field <code>string filepath = 1;</code>
     */
    protected $filepath = '';
    /**
     * disables upload of json manifest file (default false)
     *
     * Generated from protobuf field <code>bool disable_manifest = 5;</code>
     */
    protected $disable_manifest = false;
    protected $output;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $filepath
     *           see docs for templating (default {track_id}-{time})
     *     @type bool $disable_manifest
     *           disables upload of json manifest file (default false)
     *     @type \LiveKit\Proto\S3Upload $s3
     *     @type \LiveKit\Proto\GCPUpload $gcp
     *     @type \LiveKit\Proto\AzureBlobUpload $azure
     *     @type \LiveKit\Proto\AliOSSUpload $aliOSS
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * see docs for templating (default {track_id}-{time})
     *
     * Generated from protobuf field <code>string filepath = 1;</code>
     * @return string
     */
    public function getFilepath()
    {
        return $this->filepath;
    }

    /**
     * see docs for templating (default {track_id}-{time})
     *
     * Generated from protobuf field <code>string filepath = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFilepath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->filepath = $var;

        return $this;
    }

    /**
     * disables upload of json manifest file (default false)
     *
     * Generated from protobuf field <code>bool disable_manifest = 5;</code>
     * @return bool
     */
    public function getDisableManifest()
    {
        return $this->disable_manifest;
    }

    /**
     * disables upload of json manifest file (default false)
     *
     * Generated from protobuf field <code>bool disable_manifest = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableManifest(bool $var)
    {
        $this->disable_manifest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.S3Upload s3 = 2;</code>
     * @return \LiveKit\Proto\S3Upload|null
     */
    public function getS3()
    {
        return $this->readOneof(2);
    }

    public function hasS3()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.livekit.S3Upload s3 = 2;</code>
     * @param \LiveKit\Proto\S3Upload $var
     * @return $this
     */
    public function setS3(\LiveKit\Proto\S3Upload|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.GCPUpload gcp = 3;</code>
     * @return \LiveKit\Proto\GCPUpload|null
     */
    public function getGcp()
    {
        return $this->readOneof(3);
    }

    public function hasGcp()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.GCPUpload gcp = 3;</code>
     * @param \LiveKit\Proto\GCPUpload $var
     * @return $this
     */
    public function setGcp(\LiveKit\Proto\GCPUpload|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AzureBlobUpload azure = 4;</code>
     * @return \LiveKit\Proto\AzureBlobUpload|null
     */
    public function getAzure()
    {
        return $this->readOneof(4);
    }

    public function hasAzure()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.livekit.AzureBlobUpload azure = 4;</code>
     * @param \LiveKit\Proto\AzureBlobUpload $var
     * @return $this
     */
    public function setAzure(\LiveKit\Proto\AzureBlobUpload|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AliOSSUpload aliOSS = 6;</code>
     * @return \LiveKit\Proto\AliOSSUpload|null
     */
    public function getAliOSS()
    {
        return $this->readOneof(6);
    }

    public function hasAliOSS()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.livekit.AliOSSUpload aliOSS = 6;</code>
     * @param \LiveKit\Proto\AliOSSUpload $var
     * @return $this
     */
    public function setAliOSS(\LiveKit\Proto\AliOSSUpload|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOutput()
    {
        return $this->whichOneof("output");
    }

}

