<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.AutoParticipantEgress</code>
 */
class AutoParticipantEgress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.EncodedFileOutput file_outputs = 3;</code>
     */
    private $file_outputs;
    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentedFileOutput segment_outputs = 4;</code>
     */
    private $segment_outputs;
    protected $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $preset
     *           (default H264_720P_30)
     *     @type \LiveKit\Proto\EncodingOptions $advanced
     *           (optional)
     *     @type array<\LiveKit\Proto\EncodedFileOutput>|\Google\Protobuf\RepeatedField $file_outputs
     *     @type array<\LiveKit\Proto\SegmentedFileOutput>|\Google\Protobuf\RepeatedField $segment_outputs
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * (default H264_720P_30)
     *
     * Generated from protobuf field <code>.livekit.EncodingOptionsPreset preset = 1;</code>
     * @return int
     */
    public function getPreset()
    {
        return $this->readOneof(1);
    }

    public function hasPreset()
    {
        return $this->hasOneof(1);
    }

    /**
     * (default H264_720P_30)
     *
     * Generated from protobuf field <code>.livekit.EncodingOptionsPreset preset = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPreset($var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\EncodingOptionsPreset::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * (optional)
     *
     * Generated from protobuf field <code>.livekit.EncodingOptions advanced = 2;</code>
     * @return \LiveKit\Proto\EncodingOptions|null
     */
    public function getAdvanced()
    {
        return $this->readOneof(2);
    }

    public function hasAdvanced()
    {
        return $this->hasOneof(2);
    }

    /**
     * (optional)
     *
     * Generated from protobuf field <code>.livekit.EncodingOptions advanced = 2;</code>
     * @param \LiveKit\Proto\EncodingOptions $var
     * @return $this
     */
    public function setAdvanced($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\EncodingOptions::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.EncodedFileOutput file_outputs = 3;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getFileOutputs()
    {
        return $this->file_outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.EncodedFileOutput file_outputs = 3;</code>
     * @param array<\LiveKit\Proto\EncodedFileOutput>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setFileOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\EncodedFileOutput::class);
        $this->file_outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentedFileOutput segment_outputs = 4;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getSegmentOutputs()
    {
        return $this->segment_outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentedFileOutput segment_outputs = 4;</code>
     * @param array<\LiveKit\Proto\SegmentedFileOutput>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setSegmentOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SegmentedFileOutput::class);
        $this->segment_outputs = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getOptions()
    {
        return $this->whichOneof("options");
    }

}

