<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_connector_twilio.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ConnectTwilioCallResponse</code>
 */
class ConnectTwilioCallResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The websocket URL which twilio media stream will connect to
     *
     * Generated from protobuf field <code>string connect_url = 1;</code>
     */
    protected $connect_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connect_url
     *           The websocket URL which twilio media stream will connect to
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitConnectorTwilio::initOnce();
        parent::__construct($data);
    }

    /**
     * The websocket URL which twilio media stream will connect to
     *
     * Generated from protobuf field <code>string connect_url = 1;</code>
     * @return string
     */
    public function getConnectUrl()
    {
        return $this->connect_url;
    }

    /**
     * The websocket URL which twilio media stream will connect to
     *
     * Generated from protobuf field <code>string connect_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConnectUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->connect_url = $var;

        return $this;
    }

}

