<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ConnectionQualityUpdate</code>
 */
class ConnectionQualityUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.ConnectionQualityInfo updates = 1;</code>
     */
    private $updates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\ConnectionQualityInfo[] $updates
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ConnectionQualityInfo updates = 1;</code>
     * @return RepeatedField<\LiveKit\Proto\ConnectionQualityInfo>
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ConnectionQualityInfo updates = 1;</code>
     * @param \LiveKit\Proto\ConnectionQualityInfo[] $var
     * @return $this
     */
    public function setUpdates(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\ConnectionQualityInfo::class);
        $this->updates = $arr;

        return $this;
    }

}

