<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * new DataPacket API
 *
 * Generated from protobuf message <code>livekit.DataPacket</code>
 */
class DataPacket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.DataPacket.Kind kind = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $kind = 0;
    /**
     * participant identity of user that sent the message
     *
     * Generated from protobuf field <code>string participant_identity = 4;</code>
     */
    protected $participant_identity = '';
    /**
     * identities of participants who will receive the message (sent to all by default)
     *
     * Generated from protobuf field <code>repeated string destination_identities = 5;</code>
     */
    private $destination_identities;
    /**
     * sequence number of reliable packet
     *
     * Generated from protobuf field <code>uint32 sequence = 16;</code>
     */
    protected $sequence = 0;
    /**
     * sid of the user that sent the message
     *
     * Generated from protobuf field <code>string participant_sid = 17;</code>
     */
    protected $participant_sid = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *     @type string $participant_identity
     *           participant identity of user that sent the message
     *     @type string[] $destination_identities
     *           identities of participants who will receive the message (sent to all by default)
     *     @type \LiveKit\Proto\UserPacket $user
     *     @type \LiveKit\Proto\ActiveSpeakerUpdate $speaker
     *     @type \LiveKit\Proto\SipDTMF $sip_dtmf
     *     @type \LiveKit\Proto\Transcription $transcription
     *     @type \LiveKit\Proto\MetricsBatch $metrics
     *     @type \LiveKit\Proto\ChatMessage $chat_message
     *     @type \LiveKit\Proto\RpcRequest $rpc_request
     *     @type \LiveKit\Proto\RpcAck $rpc_ack
     *     @type \LiveKit\Proto\RpcResponse $rpc_response
     *     @type \LiveKit\Proto\DataStream\Header $stream_header
     *     @type \LiveKit\Proto\DataStream\Chunk $stream_chunk
     *     @type \LiveKit\Proto\DataStream\Trailer $stream_trailer
     *     @type \LiveKit\Proto\EncryptedPacket $encrypted_packet
     *     @type int $sequence
     *           sequence number of reliable packet
     *     @type string $participant_sid
     *           sid of the user that sent the message
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataPacket.Kind kind = 1 [deprecated = true];</code>
     * @return int one of the values in {@see \LiveKit\Proto\DataPacket\Kind}
     * @deprecated
     */
    public function getKind()
    {
        if ($this->kind !== 0) {
            @trigger_error('kind is deprecated.', E_USER_DEPRECATED);
        }
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataPacket.Kind kind = 1 [deprecated = true];</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\DataPacket\Kind}
     * @return $this
     * @deprecated
     */
    public function setKind(int $var)
    {
        @trigger_error('kind is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \LiveKit\Proto\DataPacket\Kind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * participant identity of user that sent the message
     *
     * Generated from protobuf field <code>string participant_identity = 4;</code>
     * @return string
     */
    public function getParticipantIdentity()
    {
        return $this->participant_identity;
    }

    /**
     * participant identity of user that sent the message
     *
     * Generated from protobuf field <code>string participant_identity = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParticipantIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->participant_identity = $var;

        return $this;
    }

    /**
     * identities of participants who will receive the message (sent to all by default)
     *
     * Generated from protobuf field <code>repeated string destination_identities = 5;</code>
     * @return RepeatedField<string>
     */
    public function getDestinationIdentities()
    {
        return $this->destination_identities;
    }

    /**
     * identities of participants who will receive the message (sent to all by default)
     *
     * Generated from protobuf field <code>repeated string destination_identities = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDestinationIdentities(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->destination_identities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.UserPacket user = 2;</code>
     * @return \LiveKit\Proto\UserPacket|null
     */
    public function getUser()
    {
        return $this->readOneof(2);
    }

    public function hasUser()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.livekit.UserPacket user = 2;</code>
     * @param \LiveKit\Proto\UserPacket $var
     * @return $this
     */
    public function setUser(\LiveKit\Proto\UserPacket|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ActiveSpeakerUpdate speaker = 3 [deprecated = true];</code>
     * @return \LiveKit\Proto\ActiveSpeakerUpdate|null
     * @deprecated
     */
    public function getSpeaker()
    {
        if ($this->hasOneof(3)) {
            @trigger_error('speaker is deprecated.', E_USER_DEPRECATED);
        }
        return $this->readOneof(3);
    }

    public function hasSpeaker()
    {
        if ($this->hasOneof(3)) {
            @trigger_error('speaker is deprecated.', E_USER_DEPRECATED);
        }
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.ActiveSpeakerUpdate speaker = 3 [deprecated = true];</code>
     * @param \LiveKit\Proto\ActiveSpeakerUpdate $var
     * @return $this
     * @deprecated
     */
    public function setSpeaker(\LiveKit\Proto\ActiveSpeakerUpdate|null $var)
    {
        @trigger_error('speaker is deprecated.', E_USER_DEPRECATED);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SipDTMF sip_dtmf = 6;</code>
     * @return \LiveKit\Proto\SipDTMF|null
     */
    public function getSipDtmf()
    {
        return $this->readOneof(6);
    }

    public function hasSipDtmf()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.livekit.SipDTMF sip_dtmf = 6;</code>
     * @param \LiveKit\Proto\SipDTMF $var
     * @return $this
     */
    public function setSipDtmf(\LiveKit\Proto\SipDTMF|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.Transcription transcription = 7;</code>
     * @return \LiveKit\Proto\Transcription|null
     */
    public function getTranscription()
    {
        return $this->readOneof(7);
    }

    public function hasTranscription()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.livekit.Transcription transcription = 7;</code>
     * @param \LiveKit\Proto\Transcription $var
     * @return $this
     */
    public function setTranscription(\LiveKit\Proto\Transcription|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.MetricsBatch metrics = 8;</code>
     * @return \LiveKit\Proto\MetricsBatch|null
     */
    public function getMetrics()
    {
        return $this->readOneof(8);
    }

    public function hasMetrics()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.livekit.MetricsBatch metrics = 8;</code>
     * @param \LiveKit\Proto\MetricsBatch $var
     * @return $this
     */
    public function setMetrics(\LiveKit\Proto\MetricsBatch|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ChatMessage chat_message = 9;</code>
     * @return \LiveKit\Proto\ChatMessage|null
     */
    public function getChatMessage()
    {
        return $this->readOneof(9);
    }

    public function hasChatMessage()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.livekit.ChatMessage chat_message = 9;</code>
     * @param \LiveKit\Proto\ChatMessage $var
     * @return $this
     */
    public function setChatMessage(\LiveKit\Proto\ChatMessage|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcRequest rpc_request = 10;</code>
     * @return \LiveKit\Proto\RpcRequest|null
     */
    public function getRpcRequest()
    {
        return $this->readOneof(10);
    }

    public function hasRpcRequest()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcRequest rpc_request = 10;</code>
     * @param \LiveKit\Proto\RpcRequest $var
     * @return $this
     */
    public function setRpcRequest(\LiveKit\Proto\RpcRequest|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcAck rpc_ack = 11;</code>
     * @return \LiveKit\Proto\RpcAck|null
     */
    public function getRpcAck()
    {
        return $this->readOneof(11);
    }

    public function hasRpcAck()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcAck rpc_ack = 11;</code>
     * @param \LiveKit\Proto\RpcAck $var
     * @return $this
     */
    public function setRpcAck(\LiveKit\Proto\RpcAck|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcResponse rpc_response = 12;</code>
     * @return \LiveKit\Proto\RpcResponse|null
     */
    public function getRpcResponse()
    {
        return $this->readOneof(12);
    }

    public function hasRpcResponse()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcResponse rpc_response = 12;</code>
     * @param \LiveKit\Proto\RpcResponse $var
     * @return $this
     */
    public function setRpcResponse(\LiveKit\Proto\RpcResponse|null $var)
    {
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Header stream_header = 13;</code>
     * @return \LiveKit\Proto\DataStream\Header|null
     */
    public function getStreamHeader()
    {
        return $this->readOneof(13);
    }

    public function hasStreamHeader()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Header stream_header = 13;</code>
     * @param \LiveKit\Proto\DataStream\Header $var
     * @return $this
     */
    public function setStreamHeader(\LiveKit\Proto\DataStream\Header|null $var)
    {
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Chunk stream_chunk = 14;</code>
     * @return \LiveKit\Proto\DataStream\Chunk|null
     */
    public function getStreamChunk()
    {
        return $this->readOneof(14);
    }

    public function hasStreamChunk()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Chunk stream_chunk = 14;</code>
     * @param \LiveKit\Proto\DataStream\Chunk $var
     * @return $this
     */
    public function setStreamChunk(\LiveKit\Proto\DataStream\Chunk|null $var)
    {
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Trailer stream_trailer = 15;</code>
     * @return \LiveKit\Proto\DataStream\Trailer|null
     */
    public function getStreamTrailer()
    {
        return $this->readOneof(15);
    }

    public function hasStreamTrailer()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Trailer stream_trailer = 15;</code>
     * @param \LiveKit\Proto\DataStream\Trailer $var
     * @return $this
     */
    public function setStreamTrailer(\LiveKit\Proto\DataStream\Trailer|null $var)
    {
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.EncryptedPacket encrypted_packet = 18;</code>
     * @return \LiveKit\Proto\EncryptedPacket|null
     */
    public function getEncryptedPacket()
    {
        return $this->readOneof(18);
    }

    public function hasEncryptedPacket()
    {
        return $this->hasOneof(18);
    }

    /**
     * Generated from protobuf field <code>.livekit.EncryptedPacket encrypted_packet = 18;</code>
     * @param \LiveKit\Proto\EncryptedPacket $var
     * @return $this
     */
    public function setEncryptedPacket(\LiveKit\Proto\EncryptedPacket|null $var)
    {
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * sequence number of reliable packet
     *
     * Generated from protobuf field <code>uint32 sequence = 16;</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * sequence number of reliable packet
     *
     * Generated from protobuf field <code>uint32 sequence = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setSequence(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * sid of the user that sent the message
     *
     * Generated from protobuf field <code>string participant_sid = 17;</code>
     * @return string
     */
    public function getParticipantSid()
    {
        return $this->participant_sid;
    }

    /**
     * sid of the user that sent the message
     *
     * Generated from protobuf field <code>string participant_sid = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setParticipantSid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->participant_sid = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

