<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.DataTrackInfo</code>
 */
class DataTrackInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Client-assigned, 16-bit identifier that will be attached to packets sent by the publisher.
     *
     * Generated from protobuf field <code>uint32 pub_handle = 1;</code>
     */
    protected $pub_handle = 0;
    /**
     * Server-assigned track identifier.
     *
     * Generated from protobuf field <code>string sid = 2;</code>
     */
    protected $sid = '';
    /**
     * Human-readable identifier (e.g., `geoLocation`, `servoPosition.x`, etc.), unique per publisher.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Method used for end-to-end encryption (E2EE) on packet payloads.
     *
     * Generated from protobuf field <code>.livekit.Encryption.Type encryption = 4;</code>
     */
    protected $encryption = 0;
    /**
     * Encoding for frame payloads on this track. If unspecified, the track is untyped.
     *
     * Generated from protobuf field <code>optional .livekit.DataTrackFrameEncoding frame_encoding = 5;</code>
     */
    protected $frame_encoding = null;
    /**
     * ID of the schema used by frames on this track if the track is typed.
     *
     * Generated from protobuf field <code>optional .livekit.DataTrackSchemaId schema = 6;</code>
     */
    protected $schema = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pub_handle
     *           Client-assigned, 16-bit identifier that will be attached to packets sent by the publisher.
     *     @type string $sid
     *           Server-assigned track identifier.
     *     @type string $name
     *           Human-readable identifier (e.g., `geoLocation`, `servoPosition.x`, etc.), unique per publisher.
     *     @type int $encryption
     *           Method used for end-to-end encryption (E2EE) on packet payloads.
     *     @type \LiveKit\Proto\DataTrackFrameEncoding $frame_encoding
     *           Encoding for frame payloads on this track. If unspecified, the track is untyped.
     *     @type \LiveKit\Proto\DataTrackSchemaId $schema
     *           ID of the schema used by frames on this track if the track is typed.
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Client-assigned, 16-bit identifier that will be attached to packets sent by the publisher.
     *
     * Generated from protobuf field <code>uint32 pub_handle = 1;</code>
     * @return int
     */
    public function getPubHandle()
    {
        return $this->pub_handle;
    }

    /**
     * Client-assigned, 16-bit identifier that will be attached to packets sent by the publisher.
     *
     * Generated from protobuf field <code>uint32 pub_handle = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPubHandle(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->pub_handle = $var;

        return $this;
    }

    /**
     * Server-assigned track identifier.
     *
     * Generated from protobuf field <code>string sid = 2;</code>
     * @return string
     */
    public function getSid()
    {
        return $this->sid;
    }

    /**
     * Server-assigned track identifier.
     *
     * Generated from protobuf field <code>string sid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sid = $var;

        return $this;
    }

    /**
     * Human-readable identifier (e.g., `geoLocation`, `servoPosition.x`, etc.), unique per publisher.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Human-readable identifier (e.g., `geoLocation`, `servoPosition.x`, etc.), unique per publisher.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Method used for end-to-end encryption (E2EE) on packet payloads.
     *
     * Generated from protobuf field <code>.livekit.Encryption.Type encryption = 4;</code>
     * @return int one of the values in {@see \LiveKit\Proto\Encryption\Type}
     */
    public function getEncryption()
    {
        return $this->encryption;
    }

    /**
     * Method used for end-to-end encryption (E2EE) on packet payloads.
     *
     * Generated from protobuf field <code>.livekit.Encryption.Type encryption = 4;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\Encryption\Type}
     * @return $this
     */
    public function setEncryption(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\Encryption\Type::class);
        $this->encryption = $var;

        return $this;
    }

    /**
     * Encoding for frame payloads on this track. If unspecified, the track is untyped.
     *
     * Generated from protobuf field <code>optional .livekit.DataTrackFrameEncoding frame_encoding = 5;</code>
     * @return \LiveKit\Proto\DataTrackFrameEncoding|null
     */
    public function getFrameEncoding()
    {
        return $this->frame_encoding;
    }

    public function hasFrameEncoding()
    {
        return isset($this->frame_encoding);
    }

    public function clearFrameEncoding()
    {
        unset($this->frame_encoding);
    }

    /**
     * Encoding for frame payloads on this track. If unspecified, the track is untyped.
     *
     * Generated from protobuf field <code>optional .livekit.DataTrackFrameEncoding frame_encoding = 5;</code>
     * @param \LiveKit\Proto\DataTrackFrameEncoding $var
     * @return $this
     */
    public function setFrameEncoding(\LiveKit\Proto\DataTrackFrameEncoding|null $var)
    {
        $this->frame_encoding = $var;

        return $this;
    }

    /**
     * ID of the schema used by frames on this track if the track is typed.
     *
     * Generated from protobuf field <code>optional .livekit.DataTrackSchemaId schema = 6;</code>
     * @return \LiveKit\Proto\DataTrackSchemaId|null
     */
    public function getSchema()
    {
        return $this->schema;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * ID of the schema used by frames on this track if the track is typed.
     *
     * Generated from protobuf field <code>optional .livekit.DataTrackSchemaId schema = 6;</code>
     * @param \LiveKit\Proto\DataTrackSchemaId $var
     * @return $this
     */
    public function setSchema(\LiveKit\Proto\DataTrackSchemaId|null $var)
    {
        $this->schema = $var;

        return $this;
    }

}

