<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A blob of data stored in a room identified by a unique key.
 *
 * Generated from protobuf message <code>livekit.DataBlob</code>
 */
class DataBlob extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique key the data blob is identified by.
     *
     * Generated from protobuf field <code>.livekit.DataBlobKey key = 1;</code>
     */
    protected $key = null;
    /**
     * Contents of the data blob. This must not exceed 50 KB.
     *
     * Generated from protobuf field <code>bytes contents = 2 [(.logger.redact_format) = "<redacted ({{ .Size }} bytes)>", (.logger.sensitivity) = SENSITIVITY_PII];</code>
     */
    protected $contents = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\DataBlobKey $key
     *           Unique key the data blob is identified by.
     *     @type string $contents
     *           Contents of the data blob. This must not exceed 50 KB.
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique key the data blob is identified by.
     *
     * Generated from protobuf field <code>.livekit.DataBlobKey key = 1;</code>
     * @return \LiveKit\Proto\DataBlobKey|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Unique key the data blob is identified by.
     *
     * Generated from protobuf field <code>.livekit.DataBlobKey key = 1;</code>
     * @param \LiveKit\Proto\DataBlobKey $var
     * @return $this
     */
    public function setKey(\LiveKit\Proto\DataBlobKey|null $var)
    {
        $this->key = $var;

        return $this;
    }

    /**
     * Contents of the data blob. This must not exceed 50 KB.
     *
     * Generated from protobuf field <code>bytes contents = 2 [(.logger.redact_format) = "<redacted ({{ .Size }} bytes)>", (.logger.sensitivity) = SENSITIVITY_PII];</code>
     * @return string
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * Contents of the data blob. This must not exceed 50 KB.
     *
     * Generated from protobuf field <code>bytes contents = 2 [(.logger.redact_format) = "<redacted ({{ .Size }} bytes)>", (.logger.sensitivity) = SENSITIVITY_PII];</code>
     * @param string $var
     * @return $this
     */
    public function setContents(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->contents = $var;

        return $this;
    }

}

