<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.Destination</code>
 */
class Destination extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string city = 1;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string country = 2;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string region = 3;</code>
     */
    protected $region = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $city
     *     @type string $country
     *     @type string $region
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string city = 1;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 2;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 3;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->region = $var;

        return $this;
    }

}

