<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.DisabledCodecs</code>
 */
class DisabledCodecs extends \Google\Protobuf\Internal\Message
{
    /**
     * disabled for both publish and subscribe
     *
     * Generated from protobuf field <code>repeated .livekit.Codec codecs = 1;</code>
     */
    private $codecs;
    /**
     * only disable for publish
     *
     * Generated from protobuf field <code>repeated .livekit.Codec publish = 2;</code>
     */
    private $publish;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\LiveKit\Proto\Codec>|\Google\Protobuf\Internal\RepeatedField $codecs
     *           disabled for both publish and subscribe
     *     @type array<\LiveKit\Proto\Codec>|\Google\Protobuf\Internal\RepeatedField $publish
     *           only disable for publish
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * disabled for both publish and subscribe
     *
     * Generated from protobuf field <code>repeated .livekit.Codec codecs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCodecs()
    {
        return $this->codecs;
    }

    /**
     * disabled for both publish and subscribe
     *
     * Generated from protobuf field <code>repeated .livekit.Codec codecs = 1;</code>
     * @param array<\LiveKit\Proto\Codec>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCodecs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\Codec::class);
        $this->codecs = $arr;

        return $this;
    }

    /**
     * only disable for publish
     *
     * Generated from protobuf field <code>repeated .livekit.Codec publish = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPublish()
    {
        return $this->publish;
    }

    /**
     * only disable for publish
     *
     * Generated from protobuf field <code>repeated .livekit.Codec publish = 2;</code>
     * @param array<\LiveKit\Proto\Codec>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPublish($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\Codec::class);
        $this->publish = $arr;

        return $this;
    }

}

