<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.EgressInfo</code>
 */
class EgressInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string egress_id = 1 [(.logger.name) = "egressID"];</code>
     */
    protected $egress_id = '';
    /**
     * Generated from protobuf field <code>string room_id = 2 [(.logger.name) = "roomID"];</code>
     */
    protected $room_id = '';
    /**
     * Generated from protobuf field <code>string room_name = 13;</code>
     */
    protected $room_name = '';
    /**
     * Generated from protobuf field <code>.livekit.EgressSourceType source_type = 26;</code>
     */
    protected $source_type = 0;
    /**
     * Generated from protobuf field <code>.livekit.EgressStatus status = 3;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 started_at = 10;</code>
     */
    protected $started_at = 0;
    /**
     * Generated from protobuf field <code>int64 ended_at = 11;</code>
     */
    protected $ended_at = 0;
    /**
     * Generated from protobuf field <code>int64 updated_at = 18;</code>
     */
    protected $updated_at = 0;
    /**
     * Generated from protobuf field <code>repeated .livekit.StreamInfo stream_results = 15;</code>
     */
    private $stream_results;
    /**
     * Generated from protobuf field <code>repeated .livekit.FileInfo file_results = 16;</code>
     */
    private $file_results;
    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentsInfo segment_results = 17;</code>
     */
    private $segment_results;
    /**
     * Generated from protobuf field <code>repeated .livekit.ImagesInfo image_results = 20;</code>
     */
    private $image_results;
    /**
     * Generated from protobuf field <code>string error = 9;</code>
     */
    protected $error = '';
    /**
     * Generated from protobuf field <code>int32 error_code = 22;</code>
     */
    protected $error_code = 0;
    /**
     * Generated from protobuf field <code>string details = 21;</code>
     */
    protected $details = '';
    /**
     * Generated from protobuf field <code>string manifest_location = 23;</code>
     */
    protected $manifest_location = '';
    /**
     * Generated from protobuf field <code>bool backup_storage_used = 25;</code>
     */
    protected $backup_storage_used = false;
    /**
     * Generated from protobuf field <code>int32 retry_count = 27;</code>
     */
    protected $retry_count = 0;
    protected $request;
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $egress_id
     *     @type string $room_id
     *     @type string $room_name
     *     @type int $source_type
     *     @type int $status
     *     @type int|string $started_at
     *     @type int|string $ended_at
     *     @type int|string $updated_at
     *     @type \LiveKit\Proto\StartEgressRequest $egress
     *     @type \LiveKit\Proto\ExportReplayRequest $replay
     *     @type \LiveKit\Proto\RoomCompositeEgressRequest $room_composite
     *           TODO: deprecate
     *     @type \LiveKit\Proto\WebEgressRequest $web
     *     @type \LiveKit\Proto\ParticipantEgressRequest $participant
     *     @type \LiveKit\Proto\TrackCompositeEgressRequest $track_composite
     *     @type \LiveKit\Proto\TrackEgressRequest $track
     *     @type \LiveKit\Proto\StreamInfo[] $stream_results
     *     @type \LiveKit\Proto\FileInfo[] $file_results
     *     @type \LiveKit\Proto\SegmentsInfo[] $segment_results
     *     @type \LiveKit\Proto\ImagesInfo[] $image_results
     *     @type string $error
     *     @type int $error_code
     *     @type string $details
     *     @type string $manifest_location
     *     @type bool $backup_storage_used
     *     @type int $retry_count
     *     @type \LiveKit\Proto\StreamInfoList $stream
     *     @type \LiveKit\Proto\FileInfo $file
     *     @type \LiveKit\Proto\SegmentsInfo $segments
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string egress_id = 1 [(.logger.name) = "egressID"];</code>
     * @return string
     */
    public function getEgressId()
    {
        return $this->egress_id;
    }

    /**
     * Generated from protobuf field <code>string egress_id = 1 [(.logger.name) = "egressID"];</code>
     * @param string $var
     * @return $this
     */
    public function setEgressId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->egress_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_id = 2 [(.logger.name) = "roomID"];</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>string room_id = 2 [(.logger.name) = "roomID"];</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_name = 13;</code>
     * @return string
     */
    public function getRoomName()
    {
        return $this->room_name;
    }

    /**
     * Generated from protobuf field <code>string room_name = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->room_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.EgressSourceType source_type = 26;</code>
     * @return int one of the values in {@see \LiveKit\Proto\EgressSourceType}
     */
    public function getSourceType()
    {
        return $this->source_type;
    }

    /**
     * Generated from protobuf field <code>.livekit.EgressSourceType source_type = 26;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\EgressSourceType}
     * @return $this
     */
    public function setSourceType(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\EgressSourceType::class);
        $this->source_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.EgressStatus status = 3;</code>
     * @return int one of the values in {@see \LiveKit\Proto\EgressStatus}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.livekit.EgressStatus status = 3;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\EgressStatus}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\EgressStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 started_at = 10;</code>
     * @return int|string
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    /**
     * Generated from protobuf field <code>int64 started_at = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartedAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ended_at = 11;</code>
     * @return int|string
     */
    public function getEndedAt()
    {
        return $this->ended_at;
    }

    /**
     * Generated from protobuf field <code>int64 ended_at = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndedAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->ended_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 18;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.StartEgressRequest egress = 29;</code>
     * @return \LiveKit\Proto\StartEgressRequest|null
     */
    public function getEgress()
    {
        return $this->readOneof(29);
    }

    public function hasEgress()
    {
        return $this->hasOneof(29);
    }

    /**
     * Generated from protobuf field <code>.livekit.StartEgressRequest egress = 29;</code>
     * @param \LiveKit\Proto\StartEgressRequest $var
     * @return $this
     */
    public function setEgress(\LiveKit\Proto\StartEgressRequest|null $var)
    {
        $this->writeOneof(29, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ExportReplayRequest replay = 30;</code>
     * @return \LiveKit\Proto\ExportReplayRequest|null
     */
    public function getReplay()
    {
        return $this->readOneof(30);
    }

    public function hasReplay()
    {
        return $this->hasOneof(30);
    }

    /**
     * Generated from protobuf field <code>.livekit.ExportReplayRequest replay = 30;</code>
     * @param \LiveKit\Proto\ExportReplayRequest $var
     * @return $this
     */
    public function setReplay(\LiveKit\Proto\ExportReplayRequest|null $var)
    {
        $this->writeOneof(30, $var);

        return $this;
    }

    /**
     * TODO: deprecate
     *
     * Generated from protobuf field <code>.livekit.RoomCompositeEgressRequest room_composite = 4;</code>
     * @return \LiveKit\Proto\RoomCompositeEgressRequest|null
     */
    public function getRoomComposite()
    {
        return $this->readOneof(4);
    }

    public function hasRoomComposite()
    {
        return $this->hasOneof(4);
    }

    /**
     * TODO: deprecate
     *
     * Generated from protobuf field <code>.livekit.RoomCompositeEgressRequest room_composite = 4;</code>
     * @param \LiveKit\Proto\RoomCompositeEgressRequest $var
     * @return $this
     */
    public function setRoomComposite(\LiveKit\Proto\RoomCompositeEgressRequest|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.WebEgressRequest web = 14;</code>
     * @return \LiveKit\Proto\WebEgressRequest|null
     */
    public function getWeb()
    {
        return $this->readOneof(14);
    }

    public function hasWeb()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.livekit.WebEgressRequest web = 14;</code>
     * @param \LiveKit\Proto\WebEgressRequest $var
     * @return $this
     */
    public function setWeb(\LiveKit\Proto\WebEgressRequest|null $var)
    {
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ParticipantEgressRequest participant = 19;</code>
     * @return \LiveKit\Proto\ParticipantEgressRequest|null
     */
    public function getParticipant()
    {
        return $this->readOneof(19);
    }

    public function hasParticipant()
    {
        return $this->hasOneof(19);
    }

    /**
     * Generated from protobuf field <code>.livekit.ParticipantEgressRequest participant = 19;</code>
     * @param \LiveKit\Proto\ParticipantEgressRequest $var
     * @return $this
     */
    public function setParticipant(\LiveKit\Proto\ParticipantEgressRequest|null $var)
    {
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackCompositeEgressRequest track_composite = 5;</code>
     * @return \LiveKit\Proto\TrackCompositeEgressRequest|null
     */
    public function getTrackComposite()
    {
        return $this->readOneof(5);
    }

    public function hasTrackComposite()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackCompositeEgressRequest track_composite = 5;</code>
     * @param \LiveKit\Proto\TrackCompositeEgressRequest $var
     * @return $this
     */
    public function setTrackComposite(\LiveKit\Proto\TrackCompositeEgressRequest|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackEgressRequest track = 6;</code>
     * @return \LiveKit\Proto\TrackEgressRequest|null
     */
    public function getTrack()
    {
        return $this->readOneof(6);
    }

    public function hasTrack()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackEgressRequest track = 6;</code>
     * @param \LiveKit\Proto\TrackEgressRequest $var
     * @return $this
     */
    public function setTrack(\LiveKit\Proto\TrackEgressRequest|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamInfo stream_results = 15;</code>
     * @return RepeatedField<\LiveKit\Proto\StreamInfo>
     */
    public function getStreamResults()
    {
        return $this->stream_results;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamInfo stream_results = 15;</code>
     * @param \LiveKit\Proto\StreamInfo[] $var
     * @return $this
     */
    public function setStreamResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\StreamInfo::class);
        $this->stream_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.FileInfo file_results = 16;</code>
     * @return RepeatedField<\LiveKit\Proto\FileInfo>
     */
    public function getFileResults()
    {
        return $this->file_results;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.FileInfo file_results = 16;</code>
     * @param \LiveKit\Proto\FileInfo[] $var
     * @return $this
     */
    public function setFileResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\FileInfo::class);
        $this->file_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentsInfo segment_results = 17;</code>
     * @return RepeatedField<\LiveKit\Proto\SegmentsInfo>
     */
    public function getSegmentResults()
    {
        return $this->segment_results;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentsInfo segment_results = 17;</code>
     * @param \LiveKit\Proto\SegmentsInfo[] $var
     * @return $this
     */
    public function setSegmentResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SegmentsInfo::class);
        $this->segment_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ImagesInfo image_results = 20;</code>
     * @return RepeatedField<\LiveKit\Proto\ImagesInfo>
     */
    public function getImageResults()
    {
        return $this->image_results;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ImagesInfo image_results = 20;</code>
     * @param \LiveKit\Proto\ImagesInfo[] $var
     * @return $this
     */
    public function setImageResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\ImagesInfo::class);
        $this->image_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 9;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setError(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 error_code = 22;</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>int32 error_code = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string details = 21;</code>
     * @return string
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>string details = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setDetails(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string manifest_location = 23;</code>
     * @return string
     */
    public function getManifestLocation()
    {
        return $this->manifest_location;
    }

    /**
     * Generated from protobuf field <code>string manifest_location = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setManifestLocation(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->manifest_location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool backup_storage_used = 25;</code>
     * @return bool
     */
    public function getBackupStorageUsed()
    {
        return $this->backup_storage_used;
    }

    /**
     * Generated from protobuf field <code>bool backup_storage_used = 25;</code>
     * @param bool $var
     * @return $this
     */
    public function setBackupStorageUsed(bool $var)
    {
        $this->backup_storage_used = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 retry_count = 27;</code>
     * @return int
     */
    public function getRetryCount()
    {
        return $this->retry_count;
    }

    /**
     * Generated from protobuf field <code>int32 retry_count = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setRetryCount(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->retry_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.StreamInfoList stream = 7 [deprecated = true];</code>
     * @return \LiveKit\Proto\StreamInfoList|null
     * @deprecated
     */
    public function getStream()
    {
        if ($this->hasOneof(7)) {
            @trigger_error('stream is deprecated.', E_USER_DEPRECATED);
        }
        return $this->readOneof(7);
    }

    public function hasStream()
    {
        if ($this->hasOneof(7)) {
            @trigger_error('stream is deprecated.', E_USER_DEPRECATED);
        }
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.livekit.StreamInfoList stream = 7 [deprecated = true];</code>
     * @param \LiveKit\Proto\StreamInfoList $var
     * @return $this
     * @deprecated
     */
    public function setStream(\LiveKit\Proto\StreamInfoList|null $var)
    {
        @trigger_error('stream is deprecated.', E_USER_DEPRECATED);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.FileInfo file = 8 [deprecated = true];</code>
     * @return \LiveKit\Proto\FileInfo|null
     * @deprecated
     */
    public function getFile()
    {
        if ($this->hasOneof(8)) {
            @trigger_error('file is deprecated.', E_USER_DEPRECATED);
        }
        return $this->readOneof(8);
    }

    public function hasFile()
    {
        if ($this->hasOneof(8)) {
            @trigger_error('file is deprecated.', E_USER_DEPRECATED);
        }
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.livekit.FileInfo file = 8 [deprecated = true];</code>
     * @param \LiveKit\Proto\FileInfo $var
     * @return $this
     * @deprecated
     */
    public function setFile(\LiveKit\Proto\FileInfo|null $var)
    {
        @trigger_error('file is deprecated.', E_USER_DEPRECATED);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SegmentsInfo segments = 12 [deprecated = true];</code>
     * @return \LiveKit\Proto\SegmentsInfo|null
     * @deprecated
     */
    public function getSegments()
    {
        if ($this->hasOneof(12)) {
            @trigger_error('segments is deprecated.', E_USER_DEPRECATED);
        }
        return $this->readOneof(12);
    }

    public function hasSegments()
    {
        if ($this->hasOneof(12)) {
            @trigger_error('segments is deprecated.', E_USER_DEPRECATED);
        }
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.livekit.SegmentsInfo segments = 12 [deprecated = true];</code>
     * @param \LiveKit\Proto\SegmentsInfo $var
     * @return $this
     * @deprecated
     */
    public function setSegments(\LiveKit\Proto\SegmentsInfo|null $var)
    {
        @trigger_error('segments is deprecated.', E_USER_DEPRECATED);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

