<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.EncodedFileOutput</code>
 */
class EncodedFileOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.EncodedFileType file_type = 1;</code>
     */
    protected $file_type = 0;
    /**
     * Generated from protobuf field <code>string filepath = 2;</code>
     */
    protected $filepath = '';
    /**
     * Generated from protobuf field <code>bool disable_manifest = 6;</code>
     */
    protected $disable_manifest = false;
    protected $output;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $file_type
     *     @type string $filepath
     *     @type bool $disable_manifest
     *     @type \LiveKit\Proto\S3Upload $s3
     *     @type \LiveKit\Proto\GCPUpload $gcp
     *     @type \LiveKit\Proto\AzureBlobUpload $azure
     *     @type \LiveKit\Proto\AliOSSUpload $aliOSS
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.EncodedFileType file_type = 1;</code>
     * @return int
     */
    public function getFileType()
    {
        return $this->file_type;
    }

    /**
     * Generated from protobuf field <code>.livekit.EncodedFileType file_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\EncodedFileType::class);
        $this->file_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filepath = 2;</code>
     * @return string
     */
    public function getFilepath()
    {
        return $this->filepath;
    }

    /**
     * Generated from protobuf field <code>string filepath = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFilepath($var)
    {
        GPBUtil::checkString($var, True);
        $this->filepath = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool disable_manifest = 6;</code>
     * @return bool
     */
    public function getDisableManifest()
    {
        return $this->disable_manifest;
    }

    /**
     * Generated from protobuf field <code>bool disable_manifest = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableManifest($var)
    {
        GPBUtil::checkBool($var);
        $this->disable_manifest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.S3Upload s3 = 3;</code>
     * @return \LiveKit\Proto\S3Upload|null
     */
    public function getS3()
    {
        return $this->readOneof(3);
    }

    public function hasS3()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.S3Upload s3 = 3;</code>
     * @param \LiveKit\Proto\S3Upload $var
     * @return $this
     */
    public function setS3($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\S3Upload::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.GCPUpload gcp = 4;</code>
     * @return \LiveKit\Proto\GCPUpload|null
     */
    public function getGcp()
    {
        return $this->readOneof(4);
    }

    public function hasGcp()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.livekit.GCPUpload gcp = 4;</code>
     * @param \LiveKit\Proto\GCPUpload $var
     * @return $this
     */
    public function setGcp($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\GCPUpload::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AzureBlobUpload azure = 5;</code>
     * @return \LiveKit\Proto\AzureBlobUpload|null
     */
    public function getAzure()
    {
        return $this->readOneof(5);
    }

    public function hasAzure()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.livekit.AzureBlobUpload azure = 5;</code>
     * @param \LiveKit\Proto\AzureBlobUpload $var
     * @return $this
     */
    public function setAzure($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\AzureBlobUpload::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AliOSSUpload aliOSS = 7;</code>
     * @return \LiveKit\Proto\AliOSSUpload|null
     */
    public function getAliOSS()
    {
        return $this->readOneof(7);
    }

    public function hasAliOSS()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.livekit.AliOSSUpload aliOSS = 7;</code>
     * @param \LiveKit\Proto\AliOSSUpload $var
     * @return $this
     */
    public function setAliOSS($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\AliOSSUpload::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOutput()
    {
        return $this->whichOneof("output");
    }

}

