<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.EncryptedPacketPayload</code>
 */
class EncryptedPacketPayload extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\UserPacket $user
     *     @type \LiveKit\Proto\ChatMessage $chat_message
     *     @type \LiveKit\Proto\RpcRequest $rpc_request
     *     @type \LiveKit\Proto\RpcAck $rpc_ack
     *     @type \LiveKit\Proto\RpcResponse $rpc_response
     *     @type \LiveKit\Proto\DataStream\Header $stream_header
     *     @type \LiveKit\Proto\DataStream\Chunk $stream_chunk
     *     @type \LiveKit\Proto\DataStream\Trailer $stream_trailer
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.UserPacket user = 1;</code>
     * @return \LiveKit\Proto\UserPacket|null
     */
    public function getUser()
    {
        return $this->readOneof(1);
    }

    public function hasUser()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.livekit.UserPacket user = 1;</code>
     * @param \LiveKit\Proto\UserPacket $var
     * @return $this
     */
    public function setUser(\LiveKit\Proto\UserPacket|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ChatMessage chat_message = 3;</code>
     * @return \LiveKit\Proto\ChatMessage|null
     */
    public function getChatMessage()
    {
        return $this->readOneof(3);
    }

    public function hasChatMessage()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.ChatMessage chat_message = 3;</code>
     * @param \LiveKit\Proto\ChatMessage $var
     * @return $this
     */
    public function setChatMessage(\LiveKit\Proto\ChatMessage|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcRequest rpc_request = 4;</code>
     * @return \LiveKit\Proto\RpcRequest|null
     */
    public function getRpcRequest()
    {
        return $this->readOneof(4);
    }

    public function hasRpcRequest()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcRequest rpc_request = 4;</code>
     * @param \LiveKit\Proto\RpcRequest $var
     * @return $this
     */
    public function setRpcRequest(\LiveKit\Proto\RpcRequest|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcAck rpc_ack = 5;</code>
     * @return \LiveKit\Proto\RpcAck|null
     */
    public function getRpcAck()
    {
        return $this->readOneof(5);
    }

    public function hasRpcAck()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcAck rpc_ack = 5;</code>
     * @param \LiveKit\Proto\RpcAck $var
     * @return $this
     */
    public function setRpcAck(\LiveKit\Proto\RpcAck|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcResponse rpc_response = 6;</code>
     * @return \LiveKit\Proto\RpcResponse|null
     */
    public function getRpcResponse()
    {
        return $this->readOneof(6);
    }

    public function hasRpcResponse()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.livekit.RpcResponse rpc_response = 6;</code>
     * @param \LiveKit\Proto\RpcResponse $var
     * @return $this
     */
    public function setRpcResponse(\LiveKit\Proto\RpcResponse|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Header stream_header = 7;</code>
     * @return \LiveKit\Proto\DataStream\Header|null
     */
    public function getStreamHeader()
    {
        return $this->readOneof(7);
    }

    public function hasStreamHeader()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Header stream_header = 7;</code>
     * @param \LiveKit\Proto\DataStream\Header $var
     * @return $this
     */
    public function setStreamHeader(\LiveKit\Proto\DataStream\Header|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Chunk stream_chunk = 8;</code>
     * @return \LiveKit\Proto\DataStream\Chunk|null
     */
    public function getStreamChunk()
    {
        return $this->readOneof(8);
    }

    public function hasStreamChunk()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Chunk stream_chunk = 8;</code>
     * @param \LiveKit\Proto\DataStream\Chunk $var
     * @return $this
     */
    public function setStreamChunk(\LiveKit\Proto\DataStream\Chunk|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Trailer stream_trailer = 9;</code>
     * @return \LiveKit\Proto\DataStream\Trailer|null
     */
    public function getStreamTrailer()
    {
        return $this->readOneof(9);
    }

    public function hasStreamTrailer()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataStream.Trailer stream_trailer = 9;</code>
     * @param \LiveKit\Proto\DataStream\Trailer $var
     * @return $this
     */
    public function setStreamTrailer(\LiveKit\Proto\DataStream\Trailer|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

