<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.GetDataBlobResponse</code>
 */
class GetDataBlobResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 request_id = 1 [(.logger.name) = "requestID"];</code>
     */
    protected $request_id = 0;
    /**
     * Generated from protobuf field <code>.livekit.DataBlob blob = 2;</code>
     */
    protected $blob = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $request_id
     *     @type \LiveKit\Proto\DataBlob $blob
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 request_id = 1 [(.logger.name) = "requestID"];</code>
     * @return int
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>uint32 request_id = 1 [(.logger.name) = "requestID"];</code>
     * @param int $var
     * @return $this
     */
    public function setRequestId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.DataBlob blob = 2;</code>
     * @return \LiveKit\Proto\DataBlob|null
     */
    public function getBlob()
    {
        return $this->blob;
    }

    public function hasBlob()
    {
        return isset($this->blob);
    }

    public function clearBlob()
    {
        unset($this->blob);
    }

    /**
     * Generated from protobuf field <code>.livekit.DataBlob blob = 2;</code>
     * @param \LiveKit\Proto\DataBlob $var
     * @return $this
     */
    public function setBlob(\LiveKit\Proto\DataBlob|null $var)
    {
        $this->blob = $var;

        return $this;
    }

}

