<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.GetDataBlobRequest</code>
 */
class GetDataBlobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 request_id = 1 [(.logger.name) = "requestID"];</code>
     */
    protected $request_id = 0;
    /**
     * Identity of the participant who owns the blob.
     *
     * Generated from protobuf field <code>string participant_identity = 2;</code>
     */
    protected $participant_identity = '';
    /**
     * Unique key of the data blob to retrieve.
     *
     * Generated from protobuf field <code>.livekit.DataBlobKey key = 3;</code>
     */
    protected $key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $request_id
     *     @type string $participant_identity
     *           Identity of the participant who owns the blob.
     *     @type \LiveKit\Proto\DataBlobKey $key
     *           Unique key of the data blob to retrieve.
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 request_id = 1 [(.logger.name) = "requestID"];</code>
     * @return int
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>uint32 request_id = 1 [(.logger.name) = "requestID"];</code>
     * @param int $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkUint32($var);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Identity of the participant who owns the blob.
     *
     * Generated from protobuf field <code>string participant_identity = 2;</code>
     * @return string
     */
    public function getParticipantIdentity()
    {
        return $this->participant_identity;
    }

    /**
     * Identity of the participant who owns the blob.
     *
     * Generated from protobuf field <code>string participant_identity = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParticipantIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->participant_identity = $var;

        return $this;
    }

    /**
     * Unique key of the data blob to retrieve.
     *
     * Generated from protobuf field <code>.livekit.DataBlobKey key = 3;</code>
     * @return \LiveKit\Proto\DataBlobKey|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Unique key of the data blob to retrieve.
     *
     * Generated from protobuf field <code>.livekit.DataBlobKey key = 3;</code>
     * @param \LiveKit\Proto\DataBlobKey $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\DataBlobKey::class);
        $this->key = $var;

        return $this;
    }

}

