<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.GetSIPOutboundTrunkResponse</code>
 */
class GetSIPOutboundTrunkResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.SIPOutboundTrunkInfo trunk = 1;</code>
     */
    protected $trunk = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\SIPOutboundTrunkInfo $trunk
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPOutboundTrunkInfo trunk = 1;</code>
     * @return \LiveKit\Proto\SIPOutboundTrunkInfo|null
     */
    public function getTrunk()
    {
        return $this->trunk;
    }

    public function hasTrunk()
    {
        return isset($this->trunk);
    }

    public function clearTrunk()
    {
        unset($this->trunk);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPOutboundTrunkInfo trunk = 1;</code>
     * @param \LiveKit\Proto\SIPOutboundTrunkInfo $var
     * @return $this
     */
    public function setTrunk($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\SIPOutboundTrunkInfo::class);
        $this->trunk = $var;

        return $this;
    }

}

