<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.GetSIPInboundTrunkResponse</code>
 */
class GetSIPInboundTrunkResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkInfo trunk = 1;</code>
     */
    protected $trunk = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\SIPInboundTrunkInfo $trunk
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkInfo trunk = 1;</code>
     * @return \LiveKit\Proto\SIPInboundTrunkInfo|null
     */
    public function getTrunk()
    {
        return $this->trunk;
    }

    public function hasTrunk()
    {
        return isset($this->trunk);
    }

    public function clearTrunk()
    {
        unset($this->trunk);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkInfo trunk = 1;</code>
     * @param \LiveKit\Proto\SIPInboundTrunkInfo $var
     * @return $this
     */
    public function setTrunk(\LiveKit\Proto\SIPInboundTrunkInfo|null $var)
    {
        $this->trunk = $var;

        return $this;
    }

}

