<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_ingress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.IngressAudioOptions</code>
 */
class IngressAudioOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.livekit.TrackSource source = 2;</code>
     */
    protected $source = 0;
    protected $encoding_options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $source
     *     @type int $preset
     *     @type \LiveKit\Proto\IngressAudioEncodingOptions $options
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitIngress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackSource source = 2;</code>
     * @return int one of the values in {@see \LiveKit\Proto\TrackSource}
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackSource source = 2;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\TrackSource}
     * @return $this
     */
    public function setSource(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\TrackSource::class);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.IngressAudioEncodingPreset preset = 3;</code>
     * @return int one of the values in {@see \LiveKit\Proto\IngressAudioEncodingPreset}
     */
    public function getPreset()
    {
        return $this->readOneof(3);
    }

    public function hasPreset()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.IngressAudioEncodingPreset preset = 3;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\IngressAudioEncodingPreset}
     * @return $this
     */
    public function setPreset(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\IngressAudioEncodingPreset::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.IngressAudioEncodingOptions options = 4;</code>
     * @return \LiveKit\Proto\IngressAudioEncodingOptions|null
     */
    public function getOptions()
    {
        return $this->readOneof(4);
    }

    public function hasOptions()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.livekit.IngressAudioEncodingOptions options = 4;</code>
     * @param \LiveKit\Proto\IngressAudioEncodingOptions $var
     * @return $this
     */
    public function setOptions(\LiveKit\Proto\IngressAudioEncodingOptions|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getEncodingOptions()
    {
        return $this->whichOneof("encoding_options");
    }

}

