<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_ingress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.InputAudioState</code>
 */
class InputAudioState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mime_type = 1;</code>
     */
    protected $mime_type = '';
    /**
     * Generated from protobuf field <code>uint32 average_bitrate = 2;</code>
     */
    protected $average_bitrate = 0;
    /**
     * Generated from protobuf field <code>uint32 channels = 3;</code>
     */
    protected $channels = 0;
    /**
     * Generated from protobuf field <code>uint32 sample_rate = 4;</code>
     */
    protected $sample_rate = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mime_type
     *     @type int $average_bitrate
     *     @type int $channels
     *     @type int $sample_rate
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitIngress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mime_type = 1;</code>
     * @return string
     */
    public function getMimeType()
    {
        return $this->mime_type;
    }

    /**
     * Generated from protobuf field <code>string mime_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMimeType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->mime_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 average_bitrate = 2;</code>
     * @return int
     */
    public function getAverageBitrate()
    {
        return $this->average_bitrate;
    }

    /**
     * Generated from protobuf field <code>uint32 average_bitrate = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAverageBitrate(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->average_bitrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 channels = 3;</code>
     * @return int
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * Generated from protobuf field <code>uint32 channels = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setChannels(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->channels = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sample_rate = 4;</code>
     * @return int
     */
    public function getSampleRate()
    {
        return $this->sample_rate;
    }

    /**
     * Generated from protobuf field <code>uint32 sample_rate = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSampleRate(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->sample_rate = $var;

        return $this;
    }

}

