<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_agent.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.Job</code>
 */
class Job extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string dispatch_id = 9 [(.logger.name) = "dispatchID"];</code>
     */
    protected $dispatch_id = '';
    /**
     * Generated from protobuf field <code>.livekit.JobType type = 2;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.livekit.Room room = 3;</code>
     */
    protected $room = null;
    /**
     * Generated from protobuf field <code>optional .livekit.ParticipantInfo participant = 4;</code>
     */
    protected $participant = null;
    /**
     * Generated from protobuf field <code>string namespace = 5 [deprecated = true];</code>
     * @deprecated
     */
    protected $namespace = '';
    /**
     * Generated from protobuf field <code>string metadata = 6 [(.logger.sensitivity) = SENSITIVITY_PII];</code>
     */
    protected $metadata = '';
    /**
     * Generated from protobuf field <code>string agent_name = 7;</code>
     */
    protected $agent_name = '';
    /**
     * Generated from protobuf field <code>.livekit.JobState state = 8;</code>
     */
    protected $state = null;
    /**
     * Generated from protobuf field <code>bool enable_recording = 10;</code>
     */
    protected $enable_recording = false;
    /**
     * Generated from protobuf field <code>string deployment = 11;</code>
     */
    protected $deployment = '';
    /**
     * Generated from protobuf field <code>map<string, string> attributes = 12 [(.logger.sensitivity) = SENSITIVITY_PII];</code>
     */
    private $attributes;
    /**
     * Generated from protobuf field <code>bool enable_redaction = 13;</code>
     */
    protected $enable_redaction = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $dispatch_id
     *     @type int $type
     *     @type \LiveKit\Proto\Room $room
     *     @type \LiveKit\Proto\ParticipantInfo $participant
     *     @type string $namespace
     *     @type string $metadata
     *     @type string $agent_name
     *     @type \LiveKit\Proto\JobState $state
     *     @type bool $enable_recording
     *     @type string $deployment
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *     @type bool $enable_redaction
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitAgent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dispatch_id = 9 [(.logger.name) = "dispatchID"];</code>
     * @return string
     */
    public function getDispatchId()
    {
        return $this->dispatch_id;
    }

    /**
     * Generated from protobuf field <code>string dispatch_id = 9 [(.logger.name) = "dispatchID"];</code>
     * @param string $var
     * @return $this
     */
    public function setDispatchId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->dispatch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.JobType type = 2;</code>
     * @return int one of the values in {@see \LiveKit\Proto\JobType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.livekit.JobType type = 2;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\JobType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\JobType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 3;</code>
     * @return \LiveKit\Proto\Room|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 3;</code>
     * @param \LiveKit\Proto\Room $var
     * @return $this
     */
    public function setRoom(\LiveKit\Proto\Room|null $var)
    {
        $this->room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .livekit.ParticipantInfo participant = 4;</code>
     * @return \LiveKit\Proto\ParticipantInfo|null
     */
    public function getParticipant()
    {
        return $this->participant;
    }

    public function hasParticipant()
    {
        return isset($this->participant);
    }

    public function clearParticipant()
    {
        unset($this->participant);
    }

    /**
     * Generated from protobuf field <code>optional .livekit.ParticipantInfo participant = 4;</code>
     * @param \LiveKit\Proto\ParticipantInfo $var
     * @return $this
     */
    public function setParticipant(\LiveKit\Proto\ParticipantInfo|null $var)
    {
        $this->participant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string namespace = 5 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getNamespace()
    {
        if ($this->namespace !== '') {
            @trigger_error('namespace is deprecated.', E_USER_DEPRECATED);
        }
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 5 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setNamespace(string $var)
    {
        @trigger_error('namespace is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string metadata = 6 [(.logger.sensitivity) = SENSITIVITY_PII];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>string metadata = 6 [(.logger.sensitivity) = SENSITIVITY_PII];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string agent_name = 7;</code>
     * @return string
     */
    public function getAgentName()
    {
        return $this->agent_name;
    }

    /**
     * Generated from protobuf field <code>string agent_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAgentName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->agent_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.JobState state = 8;</code>
     * @return \LiveKit\Proto\JobState|null
     */
    public function getState()
    {
        return $this->state;
    }

    public function hasState()
    {
        return isset($this->state);
    }

    public function clearState()
    {
        unset($this->state);
    }

    /**
     * Generated from protobuf field <code>.livekit.JobState state = 8;</code>
     * @param \LiveKit\Proto\JobState $var
     * @return $this
     */
    public function setState(\LiveKit\Proto\JobState|null $var)
    {
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_recording = 10;</code>
     * @return bool
     */
    public function getEnableRecording()
    {
        return $this->enable_recording;
    }

    /**
     * Generated from protobuf field <code>bool enable_recording = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableRecording(bool $var)
    {
        $this->enable_recording = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deployment = 11;</code>
     * @return string
     */
    public function getDeployment()
    {
        return $this->deployment;
    }

    /**
     * Generated from protobuf field <code>string deployment = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDeployment(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->deployment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 12 [(.logger.sensitivity) = SENSITIVITY_PII];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 12 [(.logger.sensitivity) = SENSITIVITY_PII];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_redaction = 13;</code>
     * @return bool
     */
    public function getEnableRedaction()
    {
        return $this->enable_redaction;
    }

    /**
     * Generated from protobuf field <code>bool enable_redaction = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableRedaction(bool $var)
    {
        $this->enable_redaction = $var;

        return $this;
    }

}

