<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_ingress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.ListIngressResponse</code>
 */
class ListIngressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.TokenPagination next_page_token = 2;</code>
     */
    protected $next_page_token = null;
    /**
     * next field id: 3
     *
     * Generated from protobuf field <code>repeated .livekit.IngressInfo items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\TokenPagination $next_page_token
     *     @type array<\LiveKit\Proto\IngressInfo>|\Google\Protobuf\Internal\RepeatedField $items
     *           next field id: 3
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitIngress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.TokenPagination next_page_token = 2;</code>
     * @return \LiveKit\Proto\TokenPagination|null
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    public function hasNextPageToken()
    {
        return isset($this->next_page_token);
    }

    public function clearNextPageToken()
    {
        unset($this->next_page_token);
    }

    /**
     * Generated from protobuf field <code>.livekit.TokenPagination next_page_token = 2;</code>
     * @param \LiveKit\Proto\TokenPagination $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\TokenPagination::class);
        $this->next_page_token = $var;

        return $this;
    }

    /**
     * next field id: 3
     *
     * Generated from protobuf field <code>repeated .livekit.IngressInfo items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * next field id: 3
     *
     * Generated from protobuf field <code>repeated .livekit.IngressInfo items = 1;</code>
     * @param array<\LiveKit\Proto\IngressInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\IngressInfo::class);
        $this->items = $arr;

        return $this;
    }

}

