<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_ingress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ListIngressRequest</code>
 */
class ListIngressRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.TokenPagination page_token = 3;</code>
     */
    protected $page_token = null;
    /**
     * when blank, lists all ingress endpoints
     *
     * Generated from protobuf field <code>string room_name = 1;</code>
     */
    protected $room_name = '';
    /**
     * (optional, filter by ingress ID)
     *
     * Generated from protobuf field <code>string ingress_id = 2 [(.logger.name) = "ingressID"];</code>
     */
    protected $ingress_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\TokenPagination $page_token
     *     @type string $room_name
     *           when blank, lists all ingress endpoints
     *     @type string $ingress_id
     *           (optional, filter by ingress ID)
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitIngress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.TokenPagination page_token = 3;</code>
     * @return \LiveKit\Proto\TokenPagination|null
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    public function hasPageToken()
    {
        return isset($this->page_token);
    }

    public function clearPageToken()
    {
        unset($this->page_token);
    }

    /**
     * Generated from protobuf field <code>.livekit.TokenPagination page_token = 3;</code>
     * @param \LiveKit\Proto\TokenPagination $var
     * @return $this
     */
    public function setPageToken(\LiveKit\Proto\TokenPagination|null $var)
    {
        $this->page_token = $var;

        return $this;
    }

    /**
     * when blank, lists all ingress endpoints
     *
     * Generated from protobuf field <code>string room_name = 1;</code>
     * @return string
     */
    public function getRoomName()
    {
        return $this->room_name;
    }

    /**
     * when blank, lists all ingress endpoints
     *
     * Generated from protobuf field <code>string room_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->room_name = $var;

        return $this;
    }

    /**
     * (optional, filter by ingress ID)
     *
     * Generated from protobuf field <code>string ingress_id = 2 [(.logger.name) = "ingressID"];</code>
     * @return string
     */
    public function getIngressId()
    {
        return $this->ingress_id;
    }

    /**
     * (optional, filter by ingress ID)
     *
     * Generated from protobuf field <code>string ingress_id = 2 [(.logger.name) = "ingressID"];</code>
     * @param string $var
     * @return $this
     */
    public function setIngressId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->ingress_id = $var;

        return $this;
    }

}

