<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * @deprecated
 * Generated from protobuf message <code>livekit.ListSIPTrunkRequest</code>
 */
class ListSIPTrunkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.Pagination page = 1;</code>
     */
    protected $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\Pagination $page
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.Pagination page = 1;</code>
     * @return \LiveKit\Proto\Pagination|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>.livekit.Pagination page = 1;</code>
     * @param \LiveKit\Proto\Pagination $var
     * @return $this
     */
    public function setPage(\LiveKit\Proto\Pagination|null $var)
    {
        $this->page = $var;

        return $this;
    }

}

