<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ListSIPInboundTrunkResponse</code>
 */
class ListSIPInboundTrunkResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.SIPInboundTrunkInfo items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\SIPInboundTrunkInfo[] $items
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SIPInboundTrunkInfo items = 1;</code>
     * @return RepeatedField<\LiveKit\Proto\SIPInboundTrunkInfo>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SIPInboundTrunkInfo items = 1;</code>
     * @param \LiveKit\Proto\SIPInboundTrunkInfo[] $var
     * @return $this
     */
    public function setItems(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SIPInboundTrunkInfo::class);
        $this->items = $arr;

        return $this;
    }

}

