<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Capture tracks directly from a room via SDK.
 * Unifies deprecated Participant, TrackComposite, and Track egress.
 *
 * Generated from protobuf message <code>livekit.MediaSource</code>
 */
class MediaSource extends \Google\Protobuf\Internal\Message
{
    /**
     * TODO: DataConfig data = 4;
     *
     * Generated from protobuf field <code>.livekit.AudioConfig audio = 3;</code>
     */
    protected $audio = null;
    protected $video;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $video_track_id
     *     @type \LiveKit\Proto\ParticipantVideo $participant_video
     *     @type \LiveKit\Proto\AudioConfig $audio
     *           TODO: DataConfig data = 4;
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string video_track_id = 1 [(.logger.name) = "videoTrackID"];</code>
     * @return string
     */
    public function getVideoTrackId()
    {
        return $this->readOneof(1);
    }

    public function hasVideoTrackId()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string video_track_id = 1 [(.logger.name) = "videoTrackID"];</code>
     * @param string $var
     * @return $this
     */
    public function setVideoTrackId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ParticipantVideo participant_video = 2;</code>
     * @return \LiveKit\Proto\ParticipantVideo|null
     */
    public function getParticipantVideo()
    {
        return $this->readOneof(2);
    }

    public function hasParticipantVideo()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.livekit.ParticipantVideo participant_video = 2;</code>
     * @param \LiveKit\Proto\ParticipantVideo $var
     * @return $this
     */
    public function setParticipantVideo(\LiveKit\Proto\ParticipantVideo|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * TODO: DataConfig data = 4;
     *
     * Generated from protobuf field <code>.livekit.AudioConfig audio = 3;</code>
     * @return \LiveKit\Proto\AudioConfig|null
     */
    public function getAudio()
    {
        return $this->audio;
    }

    public function hasAudio()
    {
        return isset($this->audio);
    }

    public function clearAudio()
    {
        unset($this->audio);
    }

    /**
     * TODO: DataConfig data = 4;
     *
     * Generated from protobuf field <code>.livekit.AudioConfig audio = 3;</code>
     * @param \LiveKit\Proto\AudioConfig $var
     * @return $this
     */
    public function setAudio(\LiveKit\Proto\AudioConfig|null $var)
    {
        $this->audio = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getVideo()
    {
        return $this->whichOneof("video");
    }

}

