<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_room.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.MuteRoomTrackResponse</code>
 */
class MuteRoomTrackResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.TrackInfo track = 1;</code>
     */
    protected $track = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\TrackInfo $track
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitRoom::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackInfo track = 1;</code>
     * @return \LiveKit\Proto\TrackInfo|null
     */
    public function getTrack()
    {
        return $this->track;
    }

    public function hasTrack()
    {
        return isset($this->track);
    }

    public function clearTrack()
    {
        unset($this->track);
    }

    /**
     * Generated from protobuf field <code>.livekit.TrackInfo track = 1;</code>
     * @param \LiveKit\Proto\TrackInfo $var
     * @return $this
     */
    public function setTrack(\LiveKit\Proto\TrackInfo|null $var)
    {
        $this->track = $var;

        return $this;
    }

}

