<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ParticipantEgressRequest</code>
 */
class ParticipantEgressRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string room_name = 1;</code>
     */
    protected $room_name = '';
    /**
     * Generated from protobuf field <code>string identity = 2;</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>bool screen_share = 3;</code>
     */
    protected $screen_share = false;
    /**
     * Generated from protobuf field <code>repeated .livekit.EncodedFileOutput file_outputs = 6;</code>
     */
    private $file_outputs;
    /**
     * Generated from protobuf field <code>repeated .livekit.StreamOutput stream_outputs = 7;</code>
     */
    private $stream_outputs;
    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentedFileOutput segment_outputs = 8;</code>
     */
    private $segment_outputs;
    /**
     * Generated from protobuf field <code>repeated .livekit.ImageOutput image_outputs = 9;</code>
     */
    private $image_outputs;
    /**
     * Generated from protobuf field <code>repeated .livekit.WebhookConfig webhooks = 10;</code>
     */
    private $webhooks;
    protected $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $room_name
     *     @type string $identity
     *     @type bool $screen_share
     *     @type int $preset
     *     @type \LiveKit\Proto\EncodingOptions $advanced
     *     @type \LiveKit\Proto\EncodedFileOutput[] $file_outputs
     *     @type \LiveKit\Proto\StreamOutput[] $stream_outputs
     *     @type \LiveKit\Proto\SegmentedFileOutput[] $segment_outputs
     *     @type \LiveKit\Proto\ImageOutput[] $image_outputs
     *     @type \LiveKit\Proto\WebhookConfig[] $webhooks
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string room_name = 1;</code>
     * @return string
     */
    public function getRoomName()
    {
        return $this->room_name;
    }

    /**
     * Generated from protobuf field <code>string room_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->room_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identity = 2;</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>string identity = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool screen_share = 3;</code>
     * @return bool
     */
    public function getScreenShare()
    {
        return $this->screen_share;
    }

    /**
     * Generated from protobuf field <code>bool screen_share = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setScreenShare(bool $var)
    {
        $this->screen_share = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.EncodingOptionsPreset preset = 4;</code>
     * @return int one of the values in {@see \LiveKit\Proto\EncodingOptionsPreset}
     */
    public function getPreset()
    {
        return $this->readOneof(4);
    }

    public function hasPreset()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.livekit.EncodingOptionsPreset preset = 4;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\EncodingOptionsPreset}
     * @return $this
     */
    public function setPreset(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\EncodingOptionsPreset::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.EncodingOptions advanced = 5;</code>
     * @return \LiveKit\Proto\EncodingOptions|null
     */
    public function getAdvanced()
    {
        return $this->readOneof(5);
    }

    public function hasAdvanced()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.livekit.EncodingOptions advanced = 5;</code>
     * @param \LiveKit\Proto\EncodingOptions $var
     * @return $this
     */
    public function setAdvanced(\LiveKit\Proto\EncodingOptions|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.EncodedFileOutput file_outputs = 6;</code>
     * @return RepeatedField<\LiveKit\Proto\EncodedFileOutput>
     */
    public function getFileOutputs()
    {
        return $this->file_outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.EncodedFileOutput file_outputs = 6;</code>
     * @param \LiveKit\Proto\EncodedFileOutput[] $var
     * @return $this
     */
    public function setFileOutputs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\EncodedFileOutput::class);
        $this->file_outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamOutput stream_outputs = 7;</code>
     * @return RepeatedField<\LiveKit\Proto\StreamOutput>
     */
    public function getStreamOutputs()
    {
        return $this->stream_outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamOutput stream_outputs = 7;</code>
     * @param \LiveKit\Proto\StreamOutput[] $var
     * @return $this
     */
    public function setStreamOutputs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\StreamOutput::class);
        $this->stream_outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentedFileOutput segment_outputs = 8;</code>
     * @return RepeatedField<\LiveKit\Proto\SegmentedFileOutput>
     */
    public function getSegmentOutputs()
    {
        return $this->segment_outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SegmentedFileOutput segment_outputs = 8;</code>
     * @param \LiveKit\Proto\SegmentedFileOutput[] $var
     * @return $this
     */
    public function setSegmentOutputs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SegmentedFileOutput::class);
        $this->segment_outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ImageOutput image_outputs = 9;</code>
     * @return RepeatedField<\LiveKit\Proto\ImageOutput>
     */
    public function getImageOutputs()
    {
        return $this->image_outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ImageOutput image_outputs = 9;</code>
     * @param \LiveKit\Proto\ImageOutput[] $var
     * @return $this
     */
    public function setImageOutputs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\ImageOutput::class);
        $this->image_outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.WebhookConfig webhooks = 10;</code>
     * @return RepeatedField<\LiveKit\Proto\WebhookConfig>
     */
    public function getWebhooks()
    {
        return $this->webhooks;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.WebhookConfig webhooks = 10;</code>
     * @param \LiveKit\Proto\WebhookConfig[] $var
     * @return $this
     */
    public function setWebhooks(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\WebhookConfig::class);
        $this->webhooks = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getOptions()
    {
        return $this->whichOneof("options");
    }

}

