<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ParticipantUpdate</code>
 */
class ParticipantUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantInfo participants = 1;</code>
     */
    private $participants;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\ParticipantInfo[] $participants
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantInfo participants = 1;</code>
     * @return RepeatedField<\LiveKit\Proto\ParticipantInfo>
     */
    public function getParticipants()
    {
        return $this->participants;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.ParticipantInfo participants = 1;</code>
     * @param \LiveKit\Proto\ParticipantInfo[] $var
     * @return $this
     */
    public function setParticipants($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\ParticipantInfo::class);
        $this->participants = $arr;

        return $this;
    }

}

