<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.ParticipantVideo</code>
 */
class ParticipantVideo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>bool prefer_screen_share = 2;</code>
     */
    protected $prefer_screen_share = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identity
     *     @type bool $prefer_screen_share
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool prefer_screen_share = 2;</code>
     * @return bool
     */
    public function getPreferScreenShare()
    {
        return $this->prefer_screen_share;
    }

    /**
     * Generated from protobuf field <code>bool prefer_screen_share = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setPreferScreenShare(bool $var)
    {
        $this->prefer_screen_share = $var;

        return $this;
    }

}

