<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.RegionSettings</code>
 */
class RegionSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.RegionInfo regions = 1;</code>
     */
    private $regions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\LiveKit\Proto\RegionInfo>|\Google\Protobuf\RepeatedField $regions
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.RegionInfo regions = 1;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getRegions()
    {
        return $this->regions;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.RegionInfo regions = 1;</code>
     * @param array<\LiveKit\Proto\RegionInfo>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setRegions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\RegionInfo::class);
        $this->regions = $arr;

        return $this;
    }

}

