<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.RoomUpdate</code>
 */
class RoomUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.Room room = 1;</code>
     */
    protected $room = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\Room $room
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 1;</code>
     * @return \LiveKit\Proto\Room|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 1;</code>
     * @param \LiveKit\Proto\Room $var
     * @return $this
     */
    public function setRoom(\LiveKit\Proto\Room|null $var)
    {
        $this->room = $var;

        return $this;
    }

}

