<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_room.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.RoomEgress</code>
 */
class RoomEgress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.RoomCompositeEgressRequest room = 1;</code>
     */
    protected $room = null;
    /**
     * Generated from protobuf field <code>.livekit.AutoParticipantEgress participant = 3;</code>
     */
    protected $participant = null;
    /**
     * Generated from protobuf field <code>.livekit.AutoTrackEgress tracks = 2;</code>
     */
    protected $tracks = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\RoomCompositeEgressRequest $room
     *     @type \LiveKit\Proto\AutoParticipantEgress $participant
     *     @type \LiveKit\Proto\AutoTrackEgress $tracks
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRoom::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.RoomCompositeEgressRequest room = 1;</code>
     * @return \LiveKit\Proto\RoomCompositeEgressRequest|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.livekit.RoomCompositeEgressRequest room = 1;</code>
     * @param \LiveKit\Proto\RoomCompositeEgressRequest $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\RoomCompositeEgressRequest::class);
        $this->room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AutoParticipantEgress participant = 3;</code>
     * @return \LiveKit\Proto\AutoParticipantEgress|null
     */
    public function getParticipant()
    {
        return $this->participant;
    }

    public function hasParticipant()
    {
        return isset($this->participant);
    }

    public function clearParticipant()
    {
        unset($this->participant);
    }

    /**
     * Generated from protobuf field <code>.livekit.AutoParticipantEgress participant = 3;</code>
     * @param \LiveKit\Proto\AutoParticipantEgress $var
     * @return $this
     */
    public function setParticipant($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\AutoParticipantEgress::class);
        $this->participant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AutoTrackEgress tracks = 2;</code>
     * @return \LiveKit\Proto\AutoTrackEgress|null
     */
    public function getTracks()
    {
        return $this->tracks;
    }

    public function hasTracks()
    {
        return isset($this->tracks);
    }

    public function clearTracks()
    {
        unset($this->tracks);
    }

    /**
     * Generated from protobuf field <code>.livekit.AutoTrackEgress tracks = 2;</code>
     * @param \LiveKit\Proto\AutoTrackEgress $var
     * @return $this
     */
    public function setTracks($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\AutoTrackEgress::class);
        $this->tracks = $var;

        return $this;
    }

}

