<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.SignalRequest</code>
 */
class SignalRequest extends \Google\Protobuf\Internal\Message
{
    protected $message;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\SessionDescription $offer
     *           participant offer for publisher
     *     @type \LiveKit\Proto\SessionDescription $answer
     *           participant answering subscriber offer
     *     @type \LiveKit\Proto\TrickleRequest $trickle
     *     @type \LiveKit\Proto\AddTrackRequest $add_track
     *     @type \LiveKit\Proto\MuteTrackRequest $mute
     *           mute the participant's published tracks
     *     @type \LiveKit\Proto\UpdateSubscription $subscription
     *           Subscribe or unsubscribe from tracks
     *     @type \LiveKit\Proto\UpdateTrackSettings $track_setting
     *           Update settings of subscribed tracks
     *     @type \LiveKit\Proto\LeaveRequest $leave
     *           Immediately terminate session
     *     @type \LiveKit\Proto\UpdateVideoLayers $update_layers
     *           Update published video layers
     *     @type \LiveKit\Proto\SubscriptionPermission $subscription_permission
     *           Update subscriber permissions
     *     @type \LiveKit\Proto\SyncState $sync_state
     *           sync client's subscribe state to server during reconnect
     *     @type \LiveKit\Proto\SimulateScenario $simulate
     *           Simulate conditions, for client validations
     *     @type int|string $ping
     *           client triggered ping to server
     *     @type \LiveKit\Proto\UpdateParticipantMetadata $update_metadata
     *           update a participant's own metadata, name, or attributes
     *           requires canUpdateOwnParticipantMetadata permission
     *     @type \LiveKit\Proto\Ping $ping_req
     *     @type \LiveKit\Proto\UpdateLocalAudioTrack $update_audio_track
     *           Update local audio track settings
     *     @type \LiveKit\Proto\UpdateLocalVideoTrack $update_video_track
     *           Update local video track settings
     *     @type \LiveKit\Proto\PublishDataTrackRequest $publish_data_track_request
     *           Publish a data track
     *     @type \LiveKit\Proto\UnpublishDataTrackRequest $unpublish_data_track_request
     *           Unpublish a data track
     *     @type \LiveKit\Proto\UpdateDataSubscription $update_data_subscription
     *           Update subscription state for one or more data tracks
     *     @type \LiveKit\Proto\StoreDataBlobRequest $store_data_blob_request
     *           Store a data blob.
     *     @type \LiveKit\Proto\GetDataBlobRequest $get_data_blob_request
     *           Retrieve a stored data blob.
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * participant offer for publisher
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 1;</code>
     * @return \LiveKit\Proto\SessionDescription|null
     */
    public function getOffer()
    {
        return $this->readOneof(1);
    }

    public function hasOffer()
    {
        return $this->hasOneof(1);
    }

    /**
     * participant offer for publisher
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 1;</code>
     * @param \LiveKit\Proto\SessionDescription $var
     * @return $this
     */
    public function setOffer(\LiveKit\Proto\SessionDescription|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * participant answering subscriber offer
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 2;</code>
     * @return \LiveKit\Proto\SessionDescription|null
     */
    public function getAnswer()
    {
        return $this->readOneof(2);
    }

    public function hasAnswer()
    {
        return $this->hasOneof(2);
    }

    /**
     * participant answering subscriber offer
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 2;</code>
     * @param \LiveKit\Proto\SessionDescription $var
     * @return $this
     */
    public function setAnswer(\LiveKit\Proto\SessionDescription|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.TrickleRequest trickle = 3;</code>
     * @return \LiveKit\Proto\TrickleRequest|null
     */
    public function getTrickle()
    {
        return $this->readOneof(3);
    }

    public function hasTrickle()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.TrickleRequest trickle = 3;</code>
     * @param \LiveKit\Proto\TrickleRequest $var
     * @return $this
     */
    public function setTrickle(\LiveKit\Proto\TrickleRequest|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.AddTrackRequest add_track = 4;</code>
     * @return \LiveKit\Proto\AddTrackRequest|null
     */
    public function getAddTrack()
    {
        return $this->readOneof(4);
    }

    public function hasAddTrack()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.livekit.AddTrackRequest add_track = 4;</code>
     * @param \LiveKit\Proto\AddTrackRequest $var
     * @return $this
     */
    public function setAddTrack(\LiveKit\Proto\AddTrackRequest|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * mute the participant's published tracks
     *
     * Generated from protobuf field <code>.livekit.MuteTrackRequest mute = 5;</code>
     * @return \LiveKit\Proto\MuteTrackRequest|null
     */
    public function getMute()
    {
        return $this->readOneof(5);
    }

    public function hasMute()
    {
        return $this->hasOneof(5);
    }

    /**
     * mute the participant's published tracks
     *
     * Generated from protobuf field <code>.livekit.MuteTrackRequest mute = 5;</code>
     * @param \LiveKit\Proto\MuteTrackRequest $var
     * @return $this
     */
    public function setMute(\LiveKit\Proto\MuteTrackRequest|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Subscribe or unsubscribe from tracks
     *
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 6;</code>
     * @return \LiveKit\Proto\UpdateSubscription|null
     */
    public function getSubscription()
    {
        return $this->readOneof(6);
    }

    public function hasSubscription()
    {
        return $this->hasOneof(6);
    }

    /**
     * Subscribe or unsubscribe from tracks
     *
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 6;</code>
     * @param \LiveKit\Proto\UpdateSubscription $var
     * @return $this
     */
    public function setSubscription(\LiveKit\Proto\UpdateSubscription|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Update settings of subscribed tracks
     *
     * Generated from protobuf field <code>.livekit.UpdateTrackSettings track_setting = 7;</code>
     * @return \LiveKit\Proto\UpdateTrackSettings|null
     */
    public function getTrackSetting()
    {
        return $this->readOneof(7);
    }

    public function hasTrackSetting()
    {
        return $this->hasOneof(7);
    }

    /**
     * Update settings of subscribed tracks
     *
     * Generated from protobuf field <code>.livekit.UpdateTrackSettings track_setting = 7;</code>
     * @param \LiveKit\Proto\UpdateTrackSettings $var
     * @return $this
     */
    public function setTrackSetting(\LiveKit\Proto\UpdateTrackSettings|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Immediately terminate session
     *
     * Generated from protobuf field <code>.livekit.LeaveRequest leave = 8;</code>
     * @return \LiveKit\Proto\LeaveRequest|null
     */
    public function getLeave()
    {
        return $this->readOneof(8);
    }

    public function hasLeave()
    {
        return $this->hasOneof(8);
    }

    /**
     * Immediately terminate session
     *
     * Generated from protobuf field <code>.livekit.LeaveRequest leave = 8;</code>
     * @param \LiveKit\Proto\LeaveRequest $var
     * @return $this
     */
    public function setLeave(\LiveKit\Proto\LeaveRequest|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Update published video layers
     *
     * Generated from protobuf field <code>.livekit.UpdateVideoLayers update_layers = 10 [deprecated = true];</code>
     * @return \LiveKit\Proto\UpdateVideoLayers|null
     * @deprecated
     */
    public function getUpdateLayers()
    {
        if ($this->hasOneof(10)) {
            @trigger_error('update_layers is deprecated.', E_USER_DEPRECATED);
        }
        return $this->readOneof(10);
    }

    public function hasUpdateLayers()
    {
        if ($this->hasOneof(10)) {
            @trigger_error('update_layers is deprecated.', E_USER_DEPRECATED);
        }
        return $this->hasOneof(10);
    }

    /**
     * Update published video layers
     *
     * Generated from protobuf field <code>.livekit.UpdateVideoLayers update_layers = 10 [deprecated = true];</code>
     * @param \LiveKit\Proto\UpdateVideoLayers $var
     * @return $this
     * @deprecated
     */
    public function setUpdateLayers(\LiveKit\Proto\UpdateVideoLayers|null $var)
    {
        @trigger_error('update_layers is deprecated.', E_USER_DEPRECATED);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Update subscriber permissions
     *
     * Generated from protobuf field <code>.livekit.SubscriptionPermission subscription_permission = 11;</code>
     * @return \LiveKit\Proto\SubscriptionPermission|null
     */
    public function getSubscriptionPermission()
    {
        return $this->readOneof(11);
    }

    public function hasSubscriptionPermission()
    {
        return $this->hasOneof(11);
    }

    /**
     * Update subscriber permissions
     *
     * Generated from protobuf field <code>.livekit.SubscriptionPermission subscription_permission = 11;</code>
     * @param \LiveKit\Proto\SubscriptionPermission $var
     * @return $this
     */
    public function setSubscriptionPermission(\LiveKit\Proto\SubscriptionPermission|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * sync client's subscribe state to server during reconnect
     *
     * Generated from protobuf field <code>.livekit.SyncState sync_state = 12;</code>
     * @return \LiveKit\Proto\SyncState|null
     */
    public function getSyncState()
    {
        return $this->readOneof(12);
    }

    public function hasSyncState()
    {
        return $this->hasOneof(12);
    }

    /**
     * sync client's subscribe state to server during reconnect
     *
     * Generated from protobuf field <code>.livekit.SyncState sync_state = 12;</code>
     * @param \LiveKit\Proto\SyncState $var
     * @return $this
     */
    public function setSyncState(\LiveKit\Proto\SyncState|null $var)
    {
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Simulate conditions, for client validations
     *
     * Generated from protobuf field <code>.livekit.SimulateScenario simulate = 13;</code>
     * @return \LiveKit\Proto\SimulateScenario|null
     */
    public function getSimulate()
    {
        return $this->readOneof(13);
    }

    public function hasSimulate()
    {
        return $this->hasOneof(13);
    }

    /**
     * Simulate conditions, for client validations
     *
     * Generated from protobuf field <code>.livekit.SimulateScenario simulate = 13;</code>
     * @param \LiveKit\Proto\SimulateScenario $var
     * @return $this
     */
    public function setSimulate(\LiveKit\Proto\SimulateScenario|null $var)
    {
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * client triggered ping to server
     *
     * Generated from protobuf field <code>int64 ping = 14;</code>
     * @return int|string
     */
    public function getPing()
    {
        return $this->readOneof(14);
    }

    public function hasPing()
    {
        return $this->hasOneof(14);
    }

    /**
     * client triggered ping to server
     *
     * Generated from protobuf field <code>int64 ping = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPing(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * update a participant's own metadata, name, or attributes
     * requires canUpdateOwnParticipantMetadata permission
     *
     * Generated from protobuf field <code>.livekit.UpdateParticipantMetadata update_metadata = 15;</code>
     * @return \LiveKit\Proto\UpdateParticipantMetadata|null
     */
    public function getUpdateMetadata()
    {
        return $this->readOneof(15);
    }

    public function hasUpdateMetadata()
    {
        return $this->hasOneof(15);
    }

    /**
     * update a participant's own metadata, name, or attributes
     * requires canUpdateOwnParticipantMetadata permission
     *
     * Generated from protobuf field <code>.livekit.UpdateParticipantMetadata update_metadata = 15;</code>
     * @param \LiveKit\Proto\UpdateParticipantMetadata $var
     * @return $this
     */
    public function setUpdateMetadata(\LiveKit\Proto\UpdateParticipantMetadata|null $var)
    {
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.Ping ping_req = 16;</code>
     * @return \LiveKit\Proto\Ping|null
     */
    public function getPingReq()
    {
        return $this->readOneof(16);
    }

    public function hasPingReq()
    {
        return $this->hasOneof(16);
    }

    /**
     * Generated from protobuf field <code>.livekit.Ping ping_req = 16;</code>
     * @param \LiveKit\Proto\Ping $var
     * @return $this
     */
    public function setPingReq(\LiveKit\Proto\Ping|null $var)
    {
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Update local audio track settings
     *
     * Generated from protobuf field <code>.livekit.UpdateLocalAudioTrack update_audio_track = 17;</code>
     * @return \LiveKit\Proto\UpdateLocalAudioTrack|null
     */
    public function getUpdateAudioTrack()
    {
        return $this->readOneof(17);
    }

    public function hasUpdateAudioTrack()
    {
        return $this->hasOneof(17);
    }

    /**
     * Update local audio track settings
     *
     * Generated from protobuf field <code>.livekit.UpdateLocalAudioTrack update_audio_track = 17;</code>
     * @param \LiveKit\Proto\UpdateLocalAudioTrack $var
     * @return $this
     */
    public function setUpdateAudioTrack(\LiveKit\Proto\UpdateLocalAudioTrack|null $var)
    {
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Update local video track settings
     *
     * Generated from protobuf field <code>.livekit.UpdateLocalVideoTrack update_video_track = 18;</code>
     * @return \LiveKit\Proto\UpdateLocalVideoTrack|null
     */
    public function getUpdateVideoTrack()
    {
        return $this->readOneof(18);
    }

    public function hasUpdateVideoTrack()
    {
        return $this->hasOneof(18);
    }

    /**
     * Update local video track settings
     *
     * Generated from protobuf field <code>.livekit.UpdateLocalVideoTrack update_video_track = 18;</code>
     * @param \LiveKit\Proto\UpdateLocalVideoTrack $var
     * @return $this
     */
    public function setUpdateVideoTrack(\LiveKit\Proto\UpdateLocalVideoTrack|null $var)
    {
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * Publish a data track
     *
     * Generated from protobuf field <code>.livekit.PublishDataTrackRequest publish_data_track_request = 19;</code>
     * @return \LiveKit\Proto\PublishDataTrackRequest|null
     */
    public function getPublishDataTrackRequest()
    {
        return $this->readOneof(19);
    }

    public function hasPublishDataTrackRequest()
    {
        return $this->hasOneof(19);
    }

    /**
     * Publish a data track
     *
     * Generated from protobuf field <code>.livekit.PublishDataTrackRequest publish_data_track_request = 19;</code>
     * @param \LiveKit\Proto\PublishDataTrackRequest $var
     * @return $this
     */
    public function setPublishDataTrackRequest(\LiveKit\Proto\PublishDataTrackRequest|null $var)
    {
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * Unpublish a data track
     *
     * Generated from protobuf field <code>.livekit.UnpublishDataTrackRequest unpublish_data_track_request = 20;</code>
     * @return \LiveKit\Proto\UnpublishDataTrackRequest|null
     */
    public function getUnpublishDataTrackRequest()
    {
        return $this->readOneof(20);
    }

    public function hasUnpublishDataTrackRequest()
    {
        return $this->hasOneof(20);
    }

    /**
     * Unpublish a data track
     *
     * Generated from protobuf field <code>.livekit.UnpublishDataTrackRequest unpublish_data_track_request = 20;</code>
     * @param \LiveKit\Proto\UnpublishDataTrackRequest $var
     * @return $this
     */
    public function setUnpublishDataTrackRequest(\LiveKit\Proto\UnpublishDataTrackRequest|null $var)
    {
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Update subscription state for one or more data tracks
     *
     * Generated from protobuf field <code>.livekit.UpdateDataSubscription update_data_subscription = 21;</code>
     * @return \LiveKit\Proto\UpdateDataSubscription|null
     */
    public function getUpdateDataSubscription()
    {
        return $this->readOneof(21);
    }

    public function hasUpdateDataSubscription()
    {
        return $this->hasOneof(21);
    }

    /**
     * Update subscription state for one or more data tracks
     *
     * Generated from protobuf field <code>.livekit.UpdateDataSubscription update_data_subscription = 21;</code>
     * @param \LiveKit\Proto\UpdateDataSubscription $var
     * @return $this
     */
    public function setUpdateDataSubscription(\LiveKit\Proto\UpdateDataSubscription|null $var)
    {
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Store a data blob.
     *
     * Generated from protobuf field <code>.livekit.StoreDataBlobRequest store_data_blob_request = 22;</code>
     * @return \LiveKit\Proto\StoreDataBlobRequest|null
     */
    public function getStoreDataBlobRequest()
    {
        return $this->readOneof(22);
    }

    public function hasStoreDataBlobRequest()
    {
        return $this->hasOneof(22);
    }

    /**
     * Store a data blob.
     *
     * Generated from protobuf field <code>.livekit.StoreDataBlobRequest store_data_blob_request = 22;</code>
     * @param \LiveKit\Proto\StoreDataBlobRequest $var
     * @return $this
     */
    public function setStoreDataBlobRequest(\LiveKit\Proto\StoreDataBlobRequest|null $var)
    {
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * Retrieve a stored data blob.
     *
     * Generated from protobuf field <code>.livekit.GetDataBlobRequest get_data_blob_request = 23;</code>
     * @return \LiveKit\Proto\GetDataBlobRequest|null
     */
    public function getGetDataBlobRequest()
    {
        return $this->readOneof(23);
    }

    public function hasGetDataBlobRequest()
    {
        return $this->hasOneof(23);
    }

    /**
     * Retrieve a stored data blob.
     *
     * Generated from protobuf field <code>.livekit.GetDataBlobRequest get_data_blob_request = 23;</code>
     * @param \LiveKit\Proto\GetDataBlobRequest $var
     * @return $this
     */
    public function setGetDataBlobRequest(\LiveKit\Proto\GetDataBlobRequest|null $var)
    {
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessage()
    {
        return $this->whichOneof("message");
    }

}

