<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_agent.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.SimulateJobRequest</code>
 */
class SimulateJobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.JobType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.livekit.Room room = 2;</code>
     */
    protected $room = null;
    /**
     * Generated from protobuf field <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    protected $participant = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \LiveKit\Proto\Room $room
     *     @type \LiveKit\Proto\ParticipantInfo $participant
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitAgent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.JobType type = 1;</code>
     * @return int one of the values in {@see \LiveKit\Proto\JobType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.livekit.JobType type = 1;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\JobType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\JobType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 2;</code>
     * @return \LiveKit\Proto\Room|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 2;</code>
     * @param \LiveKit\Proto\Room $var
     * @return $this
     */
    public function setRoom(\LiveKit\Proto\Room|null $var)
    {
        $this->room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.ParticipantInfo participant = 3;</code>
     * @return \LiveKit\Proto\ParticipantInfo|null
     */
    public function getParticipant()
    {
        return $this->participant;
    }

    public function hasParticipant()
    {
        return isset($this->participant);
    }

    public function clearParticipant()
    {
        unset($this->participant);
    }

    /**
     * Generated from protobuf field <code>.livekit.ParticipantInfo participant = 3;</code>
     * @param \LiveKit\Proto\ParticipantInfo $var
     * @return $this
     */
    public function setParticipant(\LiveKit\Proto\ParticipantInfo|null $var)
    {
        $this->participant = $var;

        return $this;
    }

}

