<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.SIPRequestDest</code>
 */
class SIPRequestDest extends \Google\Protobuf\Internal\Message
{
    protected $uri;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $raw
     *           <sip:user\@sip.example.com:5060;transport=tcp>
     *     @type \LiveKit\Proto\SIPUri $values
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * <sip:user\@sip.example.com:5060;transport=tcp>
     *
     * Generated from protobuf field <code>string raw = 1;</code>
     * @return string
     */
    public function getRaw()
    {
        return $this->readOneof(1);
    }

    public function hasRaw()
    {
        return $this->hasOneof(1);
    }

    /**
     * <sip:user\@sip.example.com:5060;transport=tcp>
     *
     * Generated from protobuf field <code>string raw = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRaw(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPUri values = 2;</code>
     * @return \LiveKit\Proto\SIPUri|null
     */
    public function getValues()
    {
        return $this->readOneof(2);
    }

    public function hasValues()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPUri values = 2;</code>
     * @param \LiveKit\Proto\SIPUri $var
     * @return $this
     */
    public function setValues(\LiveKit\Proto\SIPUri|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getUri()
    {
        return $this->whichOneof("uri");
    }

}

