<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SIPStatus is returned as an error detail in CreateSIPParticipant.
 *
 * Generated from protobuf message <code>livekit.SIPStatus</code>
 */
class SIPStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.SIPStatusCode code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string status = 2;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *     @type string $status
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPStatusCode code = 1;</code>
     * @return int one of the values in {@see \LiveKit\Proto\SIPStatusCode}
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPStatusCode code = 1;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\SIPStatusCode}
     * @return $this
     */
    public function setCode(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\SIPStatusCode::class);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

}

