<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Details of a failed SIP transfer, attached to the error.
 *
 * Generated from protobuf message <code>livekit.SIPTransferError</code>
 */
class SIPTransferError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transfer_id = 1 [(.logger.name) = "transferID"];</code>
     */
    protected $transfer_id = '';
    /**
     * Generated from protobuf field <code>.livekit.SIPTransferReason reason = 2;</code>
     */
    protected $reason = 0;
    /**
     * Set when the outcome was reported by a SIP response.
     *
     * Generated from protobuf field <code>.livekit.SIPStatus sip_status = 3;</code>
     */
    protected $sip_status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transfer_id
     *     @type int $reason
     *     @type \LiveKit\Proto\SIPStatus $sip_status
     *           Set when the outcome was reported by a SIP response.
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string transfer_id = 1 [(.logger.name) = "transferID"];</code>
     * @return string
     */
    public function getTransferId()
    {
        return $this->transfer_id;
    }

    /**
     * Generated from protobuf field <code>string transfer_id = 1 [(.logger.name) = "transferID"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransferId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->transfer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPTransferReason reason = 2;</code>
     * @return int one of the values in {@see \LiveKit\Proto\SIPTransferReason}
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPTransferReason reason = 2;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\SIPTransferReason}
     * @return $this
     */
    public function setReason(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\SIPTransferReason::class);
        $this->reason = $var;

        return $this;
    }

    /**
     * Set when the outcome was reported by a SIP response.
     *
     * Generated from protobuf field <code>.livekit.SIPStatus sip_status = 3;</code>
     * @return \LiveKit\Proto\SIPStatus|null
     */
    public function getSipStatus()
    {
        return $this->sip_status;
    }

    public function hasSipStatus()
    {
        return isset($this->sip_status);
    }

    public function clearSipStatus()
    {
        unset($this->sip_status);
    }

    /**
     * Set when the outcome was reported by a SIP response.
     *
     * Generated from protobuf field <code>.livekit.SIPStatus sip_status = 3;</code>
     * @param \LiveKit\Proto\SIPStatus $var
     * @return $this
     */
    public function setSipStatus(\LiveKit\Proto\SIPStatus|null $var)
    {
        $this->sip_status = $var;

        return $this;
    }

}

