<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.StreamStateUpdate</code>
 */
class StreamStateUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.StreamStateInfo stream_states = 1;</code>
     */
    private $stream_states;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\StreamStateInfo[] $stream_states
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamStateInfo stream_states = 1;</code>
     * @return RepeatedField<\LiveKit\Proto\StreamStateInfo>
     */
    public function getStreamStates()
    {
        return $this->stream_states;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamStateInfo stream_states = 1;</code>
     * @param \LiveKit\Proto\StreamStateInfo[] $var
     * @return $this
     */
    public function setStreamStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\StreamStateInfo::class);
        $this->stream_states = $arr;

        return $this;
    }

}

