<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.StreamInfoList</code>
 */
class StreamInfoList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .livekit.StreamInfo info = 1;</code>
     */
    private $info;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\StreamInfo[] $info
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamInfo info = 1;</code>
     * @return RepeatedField<\LiveKit\Proto\StreamInfo>
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.StreamInfo info = 1;</code>
     * @param \LiveKit\Proto\StreamInfo[] $var
     * @return $this
     */
    public function setInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\StreamInfo::class);
        $this->info = $arr;

        return $this;
    }

}

