<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.SubscriptionResponse</code>
 */
class SubscriptionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     */
    protected $track_sid = '';
    /**
     * Generated from protobuf field <code>.livekit.SubscriptionError err = 2;</code>
     */
    protected $err = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $track_sid
     *     @type int $err
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @return string
     */
    public function getTrackSid()
    {
        return $this->track_sid;
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackSid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->track_sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SubscriptionError err = 2;</code>
     * @return int one of the values in {@see \LiveKit\Proto\SubscriptionError}
     */
    public function getErr()
    {
        return $this->err;
    }

    /**
     * Generated from protobuf field <code>.livekit.SubscriptionError err = 2;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\SubscriptionError}
     * @return $this
     */
    public function setErr(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\SubscriptionError::class);
        $this->err = $var;

        return $this;
    }

}

