<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.SubscribedAudioCodecUpdate</code>
 */
class SubscribedAudioCodecUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     */
    protected $track_sid = '';
    /**
     * Generated from protobuf field <code>repeated .livekit.SubscribedAudioCodec subscribed_audio_codecs = 2;</code>
     */
    private $subscribed_audio_codecs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $track_sid
     *     @type \LiveKit\Proto\SubscribedAudioCodec[] $subscribed_audio_codecs
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @return string
     */
    public function getTrackSid()
    {
        return $this->track_sid;
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackSid($var)
    {
        GPBUtil::checkString($var, True);
        $this->track_sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SubscribedAudioCodec subscribed_audio_codecs = 2;</code>
     * @return RepeatedField<\LiveKit\Proto\SubscribedAudioCodec>
     */
    public function getSubscribedAudioCodecs()
    {
        return $this->subscribed_audio_codecs;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SubscribedAudioCodec subscribed_audio_codecs = 2;</code>
     * @param \LiveKit\Proto\SubscribedAudioCodec[] $var
     * @return $this
     */
    public function setSubscribedAudioCodecs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SubscribedAudioCodec::class);
        $this->subscribed_audio_codecs = $arr;

        return $this;
    }

}

