<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.SubscribedQuality</code>
 */
class SubscribedQuality extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.VideoQuality quality = 1;</code>
     */
    protected $quality = 0;
    /**
     * Generated from protobuf field <code>bool enabled = 2;</code>
     */
    protected $enabled = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $quality
     *     @type bool $enabled
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.VideoQuality quality = 1;</code>
     * @return int one of the values in {@see \LiveKit\Proto\VideoQuality}
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * Generated from protobuf field <code>.livekit.VideoQuality quality = 1;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\VideoQuality}
     * @return $this
     */
    public function setQuality(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\VideoQuality::class);
        $this->quality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled(bool $var)
    {
        $this->enabled = $var;

        return $this;
    }

}

