<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.SubscribedCodec</code>
 */
class SubscribedCodec extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string codec = 1;</code>
     */
    protected $codec = '';
    /**
     * Generated from protobuf field <code>repeated .livekit.SubscribedQuality qualities = 2;</code>
     */
    private $qualities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $codec
     *     @type array<\LiveKit\Proto\SubscribedQuality>|\Google\Protobuf\RepeatedField $qualities
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string codec = 1;</code>
     * @return string
     */
    public function getCodec()
    {
        return $this->codec;
    }

    /**
     * Generated from protobuf field <code>string codec = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCodec($var)
    {
        GPBUtil::checkString($var, True);
        $this->codec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SubscribedQuality qualities = 2;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getQualities()
    {
        return $this->qualities;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.SubscribedQuality qualities = 2;</code>
     * @param array<\LiveKit\Proto\SubscribedQuality>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setQualities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\SubscribedQuality::class);
        $this->qualities = $arr;

        return $this;
    }

}

