<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.SyncState</code>
 */
class SyncState extends \Google\Protobuf\Internal\Message
{
    /**
     * last subscribe/publish answer before reconnecting
     * subscribe answer if using dual peer connection
     * publish answer if using single peer connection
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 1;</code>
     */
    protected $answer = null;
    /**
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 2;</code>
     */
    protected $subscription = null;
    /**
     * Generated from protobuf field <code>repeated .livekit.TrackPublishedResponse publish_tracks = 3;</code>
     */
    private $publish_tracks;
    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelInfo data_channels = 4;</code>
     */
    private $data_channels;
    /**
     * last received server side offer/sent client side offer before reconnecting
     * received server side offer if using dual peer connection
     * sent client side offer if using single peer connection
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 5;</code>
     */
    protected $offer = null;
    /**
     * Generated from protobuf field <code>repeated string track_sids_disabled = 6;</code>
     */
    private $track_sids_disabled;
    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelReceiveState datachannel_receive_states = 7;</code>
     */
    private $datachannel_receive_states;
    /**
     * Generated from protobuf field <code>repeated .livekit.PublishDataTrackResponse publish_data_tracks = 8;</code>
     */
    private $publish_data_tracks;
    /**
     * Generated from protobuf field <code>.livekit.UpdateDataSubscription data_subscription = 9;</code>
     */
    protected $data_subscription = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\SessionDescription $answer
     *           last subscribe/publish answer before reconnecting
     *           subscribe answer if using dual peer connection
     *           publish answer if using single peer connection
     *     @type \LiveKit\Proto\UpdateSubscription $subscription
     *     @type array<\LiveKit\Proto\TrackPublishedResponse>|\Google\Protobuf\RepeatedField $publish_tracks
     *     @type array<\LiveKit\Proto\DataChannelInfo>|\Google\Protobuf\RepeatedField $data_channels
     *     @type \LiveKit\Proto\SessionDescription $offer
     *           last received server side offer/sent client side offer before reconnecting
     *           received server side offer if using dual peer connection
     *           sent client side offer if using single peer connection
     *     @type array<string>|\Google\Protobuf\RepeatedField $track_sids_disabled
     *     @type array<\LiveKit\Proto\DataChannelReceiveState>|\Google\Protobuf\RepeatedField $datachannel_receive_states
     *     @type array<\LiveKit\Proto\PublishDataTrackResponse>|\Google\Protobuf\RepeatedField $publish_data_tracks
     *     @type \LiveKit\Proto\UpdateDataSubscription $data_subscription
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * last subscribe/publish answer before reconnecting
     * subscribe answer if using dual peer connection
     * publish answer if using single peer connection
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 1;</code>
     * @return \LiveKit\Proto\SessionDescription|null
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    public function hasAnswer()
    {
        return isset($this->answer);
    }

    public function clearAnswer()
    {
        unset($this->answer);
    }

    /**
     * last subscribe/publish answer before reconnecting
     * subscribe answer if using dual peer connection
     * publish answer if using single peer connection
     *
     * Generated from protobuf field <code>.livekit.SessionDescription answer = 1;</code>
     * @param \LiveKit\Proto\SessionDescription $var
     * @return $this
     */
    public function setAnswer($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\SessionDescription::class);
        $this->answer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 2;</code>
     * @return \LiveKit\Proto\UpdateSubscription|null
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    public function hasSubscription()
    {
        return isset($this->subscription);
    }

    public function clearSubscription()
    {
        unset($this->subscription);
    }

    /**
     * Generated from protobuf field <code>.livekit.UpdateSubscription subscription = 2;</code>
     * @param \LiveKit\Proto\UpdateSubscription $var
     * @return $this
     */
    public function setSubscription($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\UpdateSubscription::class);
        $this->subscription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.TrackPublishedResponse publish_tracks = 3;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getPublishTracks()
    {
        return $this->publish_tracks;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.TrackPublishedResponse publish_tracks = 3;</code>
     * @param array<\LiveKit\Proto\TrackPublishedResponse>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setPublishTracks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\TrackPublishedResponse::class);
        $this->publish_tracks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelInfo data_channels = 4;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getDataChannels()
    {
        return $this->data_channels;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelInfo data_channels = 4;</code>
     * @param array<\LiveKit\Proto\DataChannelInfo>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setDataChannels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\DataChannelInfo::class);
        $this->data_channels = $arr;

        return $this;
    }

    /**
     * last received server side offer/sent client side offer before reconnecting
     * received server side offer if using dual peer connection
     * sent client side offer if using single peer connection
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 5;</code>
     * @return \LiveKit\Proto\SessionDescription|null
     */
    public function getOffer()
    {
        return $this->offer;
    }

    public function hasOffer()
    {
        return isset($this->offer);
    }

    public function clearOffer()
    {
        unset($this->offer);
    }

    /**
     * last received server side offer/sent client side offer before reconnecting
     * received server side offer if using dual peer connection
     * sent client side offer if using single peer connection
     *
     * Generated from protobuf field <code>.livekit.SessionDescription offer = 5;</code>
     * @param \LiveKit\Proto\SessionDescription $var
     * @return $this
     */
    public function setOffer($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\SessionDescription::class);
        $this->offer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string track_sids_disabled = 6;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getTrackSidsDisabled()
    {
        return $this->track_sids_disabled;
    }

    /**
     * Generated from protobuf field <code>repeated string track_sids_disabled = 6;</code>
     * @param array<string>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setTrackSidsDisabled($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->track_sids_disabled = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelReceiveState datachannel_receive_states = 7;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getDatachannelReceiveStates()
    {
        return $this->datachannel_receive_states;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.DataChannelReceiveState datachannel_receive_states = 7;</code>
     * @param array<\LiveKit\Proto\DataChannelReceiveState>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setDatachannelReceiveStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\DataChannelReceiveState::class);
        $this->datachannel_receive_states = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.PublishDataTrackResponse publish_data_tracks = 8;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getPublishDataTracks()
    {
        return $this->publish_data_tracks;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.PublishDataTrackResponse publish_data_tracks = 8;</code>
     * @param array<\LiveKit\Proto\PublishDataTrackResponse>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setPublishDataTracks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\PublishDataTrackResponse::class);
        $this->publish_data_tracks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.UpdateDataSubscription data_subscription = 9;</code>
     * @return \LiveKit\Proto\UpdateDataSubscription|null
     */
    public function getDataSubscription()
    {
        return $this->data_subscription;
    }

    public function hasDataSubscription()
    {
        return isset($this->data_subscription);
    }

    public function clearDataSubscription()
    {
        unset($this->data_subscription);
    }

    /**
     * Generated from protobuf field <code>.livekit.UpdateDataSubscription data_subscription = 9;</code>
     * @param \LiveKit\Proto\UpdateDataSubscription $var
     * @return $this
     */
    public function setDataSubscription($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\UpdateDataSubscription::class);
        $this->data_subscription = $var;

        return $this;
    }

}

