<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_token_source.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.TokenSourceResponse</code>
 */
class TokenSourceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string server_url = 1;</code>
     */
    protected $server_url = '';
    /**
     * Generated from protobuf field <code>string participant_token = 2;</code>
     */
    protected $participant_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $server_url
     *     @type string $participant_token
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitTokenSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string server_url = 1;</code>
     * @return string
     */
    public function getServerUrl()
    {
        return $this->server_url;
    }

    /**
     * Generated from protobuf field <code>string server_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServerUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->server_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string participant_token = 2;</code>
     * @return string
     */
    public function getParticipantToken()
    {
        return $this->participant_token;
    }

    /**
     * Generated from protobuf field <code>string participant_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParticipantToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->participant_token = $var;

        return $this;
    }

}

