<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.TrickleRequest</code>
 */
class TrickleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string candidateInit = 1;</code>
     */
    protected $candidateInit = '';
    /**
     * Generated from protobuf field <code>.livekit.SignalTarget target = 2;</code>
     */
    protected $target = 0;
    /**
     * Generated from protobuf field <code>bool final = 3;</code>
     */
    protected $final = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $candidateInit
     *     @type int $target
     *     @type bool $final
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string candidateInit = 1;</code>
     * @return string
     */
    public function getCandidateInit()
    {
        return $this->candidateInit;
    }

    /**
     * Generated from protobuf field <code>string candidateInit = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCandidateInit(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->candidateInit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SignalTarget target = 2;</code>
     * @return int one of the values in {@see \LiveKit\Proto\SignalTarget}
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Generated from protobuf field <code>.livekit.SignalTarget target = 2;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\SignalTarget}
     * @return $this
     */
    public function setTarget(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\SignalTarget::class);
        $this->target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool final = 3;</code>
     * @return bool
     */
    public function getFinal()
    {
        return $this->final;
    }

    /**
     * Generated from protobuf field <code>bool final = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setFinal(bool $var)
    {
        $this->final = $var;

        return $this;
    }

}

