<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.UnpublishDataTrackResponse</code>
 */
class UnpublishDataTrackResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Information about the unpublished track.
     *
     * Generated from protobuf field <code>.livekit.DataTrackInfo info = 1;</code>
     */
    protected $info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \LiveKit\Proto\DataTrackInfo $info
     *           Information about the unpublished track.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Information about the unpublished track.
     *
     * Generated from protobuf field <code>.livekit.DataTrackInfo info = 1;</code>
     * @return \LiveKit\Proto\DataTrackInfo|null
     */
    public function getInfo()
    {
        return $this->info;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Information about the unpublished track.
     *
     * Generated from protobuf field <code>.livekit.DataTrackInfo info = 1;</code>
     * @param \LiveKit\Proto\DataTrackInfo $var
     * @return $this
     */
    public function setInfo(\LiveKit\Proto\DataTrackInfo|null $var)
    {
        $this->info = $var;

        return $this;
    }

}

