<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.UpdateSIPInboundTrunkRequest</code>
 */
class UpdateSIPInboundTrunkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sip_trunk_id = 1 [(.logger.name) = "sipTrunkID"];</code>
     */
    protected $sip_trunk_id = '';
    protected $action;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sip_trunk_id
     *     @type \LiveKit\Proto\SIPInboundTrunkInfo $replace
     *     @type \LiveKit\Proto\SIPInboundTrunkUpdate $update
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sip_trunk_id = 1 [(.logger.name) = "sipTrunkID"];</code>
     * @return string
     */
    public function getSipTrunkId()
    {
        return $this->sip_trunk_id;
    }

    /**
     * Generated from protobuf field <code>string sip_trunk_id = 1 [(.logger.name) = "sipTrunkID"];</code>
     * @param string $var
     * @return $this
     */
    public function setSipTrunkId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sip_trunk_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkInfo replace = 2;</code>
     * @return \LiveKit\Proto\SIPInboundTrunkInfo|null
     */
    public function getReplace()
    {
        return $this->readOneof(2);
    }

    public function hasReplace()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkInfo replace = 2;</code>
     * @param \LiveKit\Proto\SIPInboundTrunkInfo $var
     * @return $this
     */
    public function setReplace(\LiveKit\Proto\SIPInboundTrunkInfo|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkUpdate update = 3;</code>
     * @return \LiveKit\Proto\SIPInboundTrunkUpdate|null
     */
    public function getUpdate()
    {
        return $this->readOneof(3);
    }

    public function hasUpdate()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPInboundTrunkUpdate update = 3;</code>
     * @param \LiveKit\Proto\SIPInboundTrunkUpdate $var
     * @return $this
     */
    public function setUpdate(\LiveKit\Proto\SIPInboundTrunkUpdate|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAction()
    {
        return $this->whichOneof("action");
    }

}

