<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_sip.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.UpdateSIPDispatchRuleRequest</code>
 */
class UpdateSIPDispatchRuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sip_dispatch_rule_id = 1 [(.logger.name) = "sipDispatchRuleID"];</code>
     */
    protected $sip_dispatch_rule_id = '';
    protected $action;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sip_dispatch_rule_id
     *     @type \LiveKit\Proto\SIPDispatchRuleInfo $replace
     *     @type \LiveKit\Proto\SIPDispatchRuleUpdate $update
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitSip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sip_dispatch_rule_id = 1 [(.logger.name) = "sipDispatchRuleID"];</code>
     * @return string
     */
    public function getSipDispatchRuleId()
    {
        return $this->sip_dispatch_rule_id;
    }

    /**
     * Generated from protobuf field <code>string sip_dispatch_rule_id = 1 [(.logger.name) = "sipDispatchRuleID"];</code>
     * @param string $var
     * @return $this
     */
    public function setSipDispatchRuleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sip_dispatch_rule_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPDispatchRuleInfo replace = 2;</code>
     * @return \LiveKit\Proto\SIPDispatchRuleInfo|null
     */
    public function getReplace()
    {
        return $this->readOneof(2);
    }

    public function hasReplace()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPDispatchRuleInfo replace = 2;</code>
     * @param \LiveKit\Proto\SIPDispatchRuleInfo $var
     * @return $this
     */
    public function setReplace($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\SIPDispatchRuleInfo::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPDispatchRuleUpdate update = 3;</code>
     * @return \LiveKit\Proto\SIPDispatchRuleUpdate|null
     */
    public function getUpdate()
    {
        return $this->readOneof(3);
    }

    public function hasUpdate()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.livekit.SIPDispatchRuleUpdate update = 3;</code>
     * @param \LiveKit\Proto\SIPDispatchRuleUpdate $var
     * @return $this
     */
    public function setUpdate($var)
    {
        GPBUtil::checkMessage($var, \LiveKit\Proto\SIPDispatchRuleUpdate::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAction()
    {
        return $this->whichOneof("action");
    }

}

