<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>livekit.UpdateLocalAudioTrack</code>
 */
class UpdateLocalAudioTrack extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     */
    protected $track_sid = '';
    /**
     * Generated from protobuf field <code>repeated .livekit.AudioTrackFeature features = 2;</code>
     */
    private $features;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $track_sid
     *     @type array<int>|\Google\Protobuf\RepeatedField $features
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @return string
     */
    public function getTrackSid()
    {
        return $this->track_sid;
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackSid($var)
    {
        GPBUtil::checkString($var, True);
        $this->track_sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.AudioTrackFeature features = 2;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.AudioTrackFeature features = 2;</code>
     * @param array<int>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \LiveKit\Proto\AudioTrackFeature::class);
        $this->features = $arr;

        return $this;
    }

}

