<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_rtc.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * message to indicate published video track dimensions are changing
 *
 * @deprecated
 * Generated from protobuf message <code>livekit.UpdateVideoLayers</code>
 */
class UpdateVideoLayers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     */
    protected $track_sid = '';
    /**
     * Generated from protobuf field <code>repeated .livekit.VideoLayer layers = 2;</code>
     */
    private $layers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $track_sid
     *     @type array<\LiveKit\Proto\VideoLayer>|\Google\Protobuf\RepeatedField $layers
     * }
     */
    public function __construct($data = NULL) {
        \LiveKit\Proto\Meta\LivekitRtc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @return string
     */
    public function getTrackSid()
    {
        return $this->track_sid;
    }

    /**
     * Generated from protobuf field <code>string track_sid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackSid($var)
    {
        GPBUtil::checkString($var, True);
        $this->track_sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.VideoLayer layers = 2;</code>
     * @return \Google\Protobuf\RepeatedField
     */
    public function getLayers()
    {
        return $this->layers;
    }

    /**
     * Generated from protobuf field <code>repeated .livekit.VideoLayer layers = 2;</code>
     * @param array<\LiveKit\Proto\VideoLayer>|\Google\Protobuf\RepeatedField $var
     * @return $this
     */
    public function setLayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \LiveKit\Proto\VideoLayer::class);
        $this->layers = $arr;

        return $this;
    }

}

