<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_egress.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.UpdateLayoutRequest</code>
 */
class UpdateLayoutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string egress_id = 1 [(.logger.name) = "egressID"];</code>
     */
    protected $egress_id = '';
    /**
     * Generated from protobuf field <code>string layout = 2;</code>
     */
    protected $layout = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $egress_id
     *     @type string $layout
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitEgress::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string egress_id = 1 [(.logger.name) = "egressID"];</code>
     * @return string
     */
    public function getEgressId()
    {
        return $this->egress_id;
    }

    /**
     * Generated from protobuf field <code>string egress_id = 1 [(.logger.name) = "egressID"];</code>
     * @param string $var
     * @return $this
     */
    public function setEgressId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->egress_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string layout = 2;</code>
     * @return string
     */
    public function getLayout()
    {
        return $this->layout;
    }

    /**
     * Generated from protobuf field <code>string layout = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLayout(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->layout = $var;

        return $this;
    }

}

