<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_models.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.VideoConfiguration</code>
 */
class VideoConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting hardware_encoder = 1;</code>
     */
    protected $hardware_encoder = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $hardware_encoder
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitModels::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting hardware_encoder = 1;</code>
     * @return int one of the values in {@see \LiveKit\Proto\ClientConfigSetting}
     */
    public function getHardwareEncoder()
    {
        return $this->hardware_encoder;
    }

    /**
     * Generated from protobuf field <code>.livekit.ClientConfigSetting hardware_encoder = 1;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\ClientConfigSetting}
     * @return $this
     */
    public function setHardwareEncoder(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\ClientConfigSetting::class);
        $this->hardware_encoder = $var;

        return $this;
    }

}

