<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_webhook.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.WebhookEvent</code>
 */
class WebhookEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended, agent_job_started, agent_job_ended
     *
     * Generated from protobuf field <code>string event = 1;</code>
     */
    protected $event = '';
    /**
     * Generated from protobuf field <code>.livekit.Room room = 2;</code>
     */
    protected $room = null;
    /**
     * set when event is participant_* or track_*
     *
     * Generated from protobuf field <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    protected $participant = null;
    /**
     * set when event is egress_*
     *
     * Generated from protobuf field <code>.livekit.EgressInfo egress_info = 9;</code>
     */
    protected $egress_info = null;
    /**
     * set when event is ingress_*
     *
     * Generated from protobuf field <code>.livekit.IngressInfo ingress_info = 10;</code>
     */
    protected $ingress_info = null;
    /**
     * set when event is track_*
     *
     * Generated from protobuf field <code>.livekit.TrackInfo track = 8;</code>
     */
    protected $track = null;
    /**
     * set when event is agent_job_*
     *
     * Generated from protobuf field <code>.livekit.Job job = 12;</code>
     */
    protected $job = null;
    /**
     * unique event uuid
     *
     * Generated from protobuf field <code>string id = 6;</code>
     */
    protected $id = '';
    /**
     * timestamp in seconds
     *
     * Generated from protobuf field <code>int64 created_at = 7;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @deprecated
     */
    protected $num_dropped = 0;
    /**
     * set when event is room_finished
     *
     * Generated from protobuf field <code>.livekit.RoomEndReason room_end_reason = 13;</code>
     */
    protected $room_end_reason = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $event
     *           one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     *           track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     *           ingress_started, ingress_ended, agent_job_started, agent_job_ended
     *     @type \LiveKit\Proto\Room $room
     *     @type \LiveKit\Proto\ParticipantInfo $participant
     *           set when event is participant_* or track_*
     *     @type \LiveKit\Proto\EgressInfo $egress_info
     *           set when event is egress_*
     *     @type \LiveKit\Proto\IngressInfo $ingress_info
     *           set when event is ingress_*
     *     @type \LiveKit\Proto\TrackInfo $track
     *           set when event is track_*
     *     @type \LiveKit\Proto\Job $job
     *           set when event is agent_job_*
     *     @type string $id
     *           unique event uuid
     *     @type int|string $created_at
     *           timestamp in seconds
     *     @type int $num_dropped
     *     @type int $room_end_reason
     *           set when event is room_finished
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\LiveKit\LivekitWebhook::initOnce();
        parent::__construct($data);
    }

    /**
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended, agent_job_started, agent_job_ended
     *
     * Generated from protobuf field <code>string event = 1;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended, agent_job_started, agent_job_ended
     *
     * Generated from protobuf field <code>string event = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 2;</code>
     * @return \LiveKit\Proto\Room|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.livekit.Room room = 2;</code>
     * @param \LiveKit\Proto\Room $var
     * @return $this
     */
    public function setRoom(\LiveKit\Proto\Room|null $var)
    {
        $this->room = $var;

        return $this;
    }

    /**
     * set when event is participant_* or track_*
     *
     * Generated from protobuf field <code>.livekit.ParticipantInfo participant = 3;</code>
     * @return \LiveKit\Proto\ParticipantInfo|null
     */
    public function getParticipant()
    {
        return $this->participant;
    }

    public function hasParticipant()
    {
        return isset($this->participant);
    }

    public function clearParticipant()
    {
        unset($this->participant);
    }

    /**
     * set when event is participant_* or track_*
     *
     * Generated from protobuf field <code>.livekit.ParticipantInfo participant = 3;</code>
     * @param \LiveKit\Proto\ParticipantInfo $var
     * @return $this
     */
    public function setParticipant(\LiveKit\Proto\ParticipantInfo|null $var)
    {
        $this->participant = $var;

        return $this;
    }

    /**
     * set when event is egress_*
     *
     * Generated from protobuf field <code>.livekit.EgressInfo egress_info = 9;</code>
     * @return \LiveKit\Proto\EgressInfo|null
     */
    public function getEgressInfo()
    {
        return $this->egress_info;
    }

    public function hasEgressInfo()
    {
        return isset($this->egress_info);
    }

    public function clearEgressInfo()
    {
        unset($this->egress_info);
    }

    /**
     * set when event is egress_*
     *
     * Generated from protobuf field <code>.livekit.EgressInfo egress_info = 9;</code>
     * @param \LiveKit\Proto\EgressInfo $var
     * @return $this
     */
    public function setEgressInfo(\LiveKit\Proto\EgressInfo|null $var)
    {
        $this->egress_info = $var;

        return $this;
    }

    /**
     * set when event is ingress_*
     *
     * Generated from protobuf field <code>.livekit.IngressInfo ingress_info = 10;</code>
     * @return \LiveKit\Proto\IngressInfo|null
     */
    public function getIngressInfo()
    {
        return $this->ingress_info;
    }

    public function hasIngressInfo()
    {
        return isset($this->ingress_info);
    }

    public function clearIngressInfo()
    {
        unset($this->ingress_info);
    }

    /**
     * set when event is ingress_*
     *
     * Generated from protobuf field <code>.livekit.IngressInfo ingress_info = 10;</code>
     * @param \LiveKit\Proto\IngressInfo $var
     * @return $this
     */
    public function setIngressInfo(\LiveKit\Proto\IngressInfo|null $var)
    {
        $this->ingress_info = $var;

        return $this;
    }

    /**
     * set when event is track_*
     *
     * Generated from protobuf field <code>.livekit.TrackInfo track = 8;</code>
     * @return \LiveKit\Proto\TrackInfo|null
     */
    public function getTrack()
    {
        return $this->track;
    }

    public function hasTrack()
    {
        return isset($this->track);
    }

    public function clearTrack()
    {
        unset($this->track);
    }

    /**
     * set when event is track_*
     *
     * Generated from protobuf field <code>.livekit.TrackInfo track = 8;</code>
     * @param \LiveKit\Proto\TrackInfo $var
     * @return $this
     */
    public function setTrack(\LiveKit\Proto\TrackInfo|null $var)
    {
        $this->track = $var;

        return $this;
    }

    /**
     * set when event is agent_job_*
     *
     * Generated from protobuf field <code>.livekit.Job job = 12;</code>
     * @return \LiveKit\Proto\Job|null
     */
    public function getJob()
    {
        return $this->job;
    }

    public function hasJob()
    {
        return isset($this->job);
    }

    public function clearJob()
    {
        unset($this->job);
    }

    /**
     * set when event is agent_job_*
     *
     * Generated from protobuf field <code>.livekit.Job job = 12;</code>
     * @param \LiveKit\Proto\Job $var
     * @return $this
     */
    public function setJob(\LiveKit\Proto\Job|null $var)
    {
        $this->job = $var;

        return $this;
    }

    /**
     * unique event uuid
     *
     * Generated from protobuf field <code>string id = 6;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * unique event uuid
     *
     * Generated from protobuf field <code>string id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * timestamp in seconds
     *
     * Generated from protobuf field <code>int64 created_at = 7;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * timestamp in seconds
     *
     * Generated from protobuf field <code>int64 created_at = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getNumDropped()
    {
        if ($this->num_dropped !== 0) {
            @trigger_error('num_dropped is deprecated.', E_USER_DEPRECATED);
        }
        return $this->num_dropped;
    }

    /**
     * Generated from protobuf field <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setNumDropped(int $var)
    {
        @trigger_error('num_dropped is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkInt32($var);
        $this->num_dropped = $var;

        return $this;
    }

    /**
     * set when event is room_finished
     *
     * Generated from protobuf field <code>.livekit.RoomEndReason room_end_reason = 13;</code>
     * @return int one of the values in {@see \LiveKit\Proto\RoomEndReason}
     */
    public function getRoomEndReason()
    {
        return $this->room_end_reason;
    }

    /**
     * set when event is room_finished
     *
     * Generated from protobuf field <code>.livekit.RoomEndReason room_end_reason = 13;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\RoomEndReason}
     * @return $this
     */
    public function setRoomEndReason(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\RoomEndReason::class);
        $this->room_end_reason = $var;

        return $this;
    }

}

