<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livekit_connector_whatsapp.proto

namespace LiveKit\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>livekit.WhatsAppCall</code>
 */
class WhatsAppCall extends \Google\Protobuf\Internal\Message
{
    /**
     * list of call ids that are currently active
     *
     * Generated from protobuf field <code>string whatsapp_call_id = 1 [(.logger.name) = "whatsappCallID"];</code>
     */
    protected $whatsapp_call_id = '';
    /**
     * Direction of the call
     *
     * Generated from protobuf field <code>.livekit.WhatsAppCallDirection direction = 2;</code>
     */
    protected $direction = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $whatsapp_call_id
     *           list of call ids that are currently active
     *     @type int $direction
     *           Direction of the call
     * }
     */
    public function __construct($data = null)
    {
        \LiveKit\Proto\Meta\LivekitConnectorWhatsapp::initOnce();
        parent::__construct($data);
    }

    /**
     * list of call ids that are currently active
     *
     * Generated from protobuf field <code>string whatsapp_call_id = 1 [(.logger.name) = "whatsappCallID"];</code>
     * @return string
     */
    public function getWhatsappCallId()
    {
        return $this->whatsapp_call_id;
    }

    /**
     * list of call ids that are currently active
     *
     * Generated from protobuf field <code>string whatsapp_call_id = 1 [(.logger.name) = "whatsappCallID"];</code>
     * @param string $var
     * @return $this
     */
    public function setWhatsappCallId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->whatsapp_call_id = $var;

        return $this;
    }

    /**
     * Direction of the call
     *
     * Generated from protobuf field <code>.livekit.WhatsAppCallDirection direction = 2;</code>
     * @return int one of the values in {@see \LiveKit\Proto\WhatsAppCallDirection}
     */
    public function getDirection()
    {
        return $this->direction;
    }

    /**
     * Direction of the call
     *
     * Generated from protobuf field <code>.livekit.WhatsAppCallDirection direction = 2;</code>
     * @param int $var one of the values in {@see \LiveKit\Proto\WhatsAppCallDirection}
     * @return $this
     */
    public function setDirection(int $var)
    {
        GPBUtil::checkEnum($var, \LiveKit\Proto\WhatsAppCallDirection::class);
        $this->direction = $var;

        return $this;
    }

}

